import { describe, expect, it, vi } from "vitest";

import {
  FinalCutApprovalRequiredError,
  createCreateFinalCutGenerateTaskUseCase,
} from "../src/index";

describe("create final cut generate task use case", () => {
  it("rejects final cut generation when any shot is not approved", async () => {
    const useCase = createCreateFinalCutGenerateTaskUseCase({
      projectRepository: {
        insert: vi.fn(),
        findById: vi.fn().mockResolvedValue({
          id: "proj_1",
          storageDir: "projects/proj_1-my-story",
          currentVideoBatchId: "video_batch_1",
          status: "videos_in_review",
        }),
        listAll: vi.fn(),
        updatePremiseMetadata: vi.fn(),
        updateCurrentMasterPlot: vi.fn(),
        updateCurrentCharacterSheetBatch: vi.fn(),
        updateCurrentStoryboard: vi.fn(),
        updateCurrentShotScript: vi.fn(),
        updateCurrentImageBatch: vi.fn(),
        updateCurrentVideoBatch: vi.fn(),
        updateStatus: vi.fn(),
      },
      videoRepository: {
        insertBatch: vi.fn(),
        findBatchById: vi.fn().mockResolvedValue({
          id: "video_batch_1",
          sourceImageBatchId: "image_batch_1",
          sourceShotScriptId: "shot_script_1",
          shotCount: 2,
          updatedAt: "2026-03-31T00:00:00.000Z",
        }),
        findCurrentBatchByProjectId: vi.fn(),
        listSegmentsByBatchId: vi.fn().mockResolvedValue([
          {
            id: "video_1",
            projectId: "proj_1",
            batchId: "video_batch_1",
            sourceImageBatchId: "image_batch_1",
            sourceShotScriptId: "shot_script_1",
            shotId: "shot_1",
            shotCode: "SC01-SG01-SH01",
            sceneId: "scene_1",
            segmentId: "segment_1",
            segmentOrder: 1,
            shotOrder: 1,
            frameDependency: "start_frame_only",
            status: "approved",
            promptTextSeed: "seed 1",
            promptTextCurrent: "current 1",
            promptUpdatedAt: "2026-03-31T00:00:00.000Z",
            videoAssetPath: "videos/batches/video_batch_1/shots/scene_1__segment_1__shot_1/current.mp4",
            thumbnailAssetPath: null,
            durationSec: 3,
            provider: "openai",
            model: "sora-2-all",
            updatedAt: "2026-03-31T00:00:00.000Z",
            approvedAt: "2026-03-31T00:00:00.000Z",
            sourceTaskId: "task_segment_video_1",
            projectStorageDir: "projects/proj_1-my-story",
            storageDir: "ignored",
            currentVideoRelPath: "ignored",
            currentMetadataRelPath: "ignored",
            thumbnailRelPath: "ignored",
            versionsStorageDir: "ignored",
          },
          {
            id: "video_2",
            projectId: "proj_1",
            batchId: "video_batch_1",
            sourceImageBatchId: "image_batch_1",
            sourceShotScriptId: "shot_script_1",
            shotId: "shot_2",
            shotCode: "SC01-SG01-SH02",
            sceneId: "scene_1",
            segmentId: "segment_1",
            segmentOrder: 1,
            shotOrder: 2,
            frameDependency: "start_frame_only",
            status: "in_review",
            promptTextSeed: "seed 2",
            promptTextCurrent: "current 2",
            promptUpdatedAt: "2026-03-31T00:00:00.000Z",
            videoAssetPath: "videos/batches/video_batch_1/shots/scene_1__segment_1__shot_2/current.mp4",
            thumbnailAssetPath: null,
            durationSec: 3,
            provider: "openai",
            model: "sora-2-all",
            updatedAt: "2026-03-31T00:00:00.000Z",
            approvedAt: null,
            sourceTaskId: "task_segment_video_2",
            projectStorageDir: "projects/proj_1-my-story",
            storageDir: "ignored",
            currentVideoRelPath: "ignored",
            currentMetadataRelPath: "ignored",
            thumbnailRelPath: "ignored",
            versionsStorageDir: "ignored",
          },
        ]),
        insertSegment: vi.fn(),
        findSegmentById: vi.fn(),
        findCurrentSegmentByProjectIdAndSegmentId: vi.fn(),
        findCurrentSegmentByProjectIdAndSceneIdAndSegmentId: vi.fn(),
        updateSegment: vi.fn(),
        findCurrentFinalCutByProjectId: vi.fn(),
        upsertFinalCut: vi.fn(),
      },
      taskRepository: {
        insert: vi.fn(),
        findById: vi.fn(),
        findLatestByProjectId: vi.fn(),
        delete: vi.fn(),
        markRunning: vi.fn(),
        markSucceeded: vi.fn(),
        markFailed: vi.fn(),
      },
      taskFileStorage: {
        createTaskArtifacts: vi.fn(),
        readTaskInput: vi.fn(),
        writeTaskOutput: vi.fn(),
        appendTaskLog: vi.fn(),
      },
      taskQueue: { enqueue: vi.fn() },
      taskIdGenerator: { generateTaskId: () => "task_final_cut_1" },
      clock: { now: () => "2026-03-31T00:00:00.000Z" },
    });

    await expect(useCase.execute({ projectId: "proj_1" })).rejects.toBeInstanceOf(
      FinalCutApprovalRequiredError,
    );
  });
});
