import { describe, expect, it, vi } from "vitest";

import {
  CurrentMasterPlotNotFoundError,
  ProjectNotFoundError,
  ProjectValidationError,
  createCreateSceneSheetsGenerateTaskUseCase,
} from "../src/index";

describe("create scene sheets generate task use case", () => {
  it("creates a pending scene-sheet batch task from approved master plot and character sheets", async () => {
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_20260321_ab12cd",
        name: "My Story",
        slug: "my-story",
        storageDir: "projects/proj_20260321_ab12cd-my-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "mp_20260321_ab12cd",
        currentCharacterSheetBatchId: "char_batch_20260321_ab12cd",
        currentSceneSheetBatchId: null,
        currentStoryboardId: null,
        currentShotScriptId: null,
        currentImageBatchId: null,
        currentVideoBatchId: null,
        status: "character_sheets_approved",
        createdAt: "2026-03-21T11:59:00.000Z",
        updatedAt: "2026-03-21T12:00:00.000Z",
        premiseUpdatedAt: "2026-03-21T12:00:00.000Z",
        visualStyleText: "赛璐璐动画，潮湿冷蓝夜景",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentSceneSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateCurrentVideoBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn(),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn(),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const taskQueue = {
      enqueue: vi.fn(),
    };
    const masterPlotStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeCurrentMasterPlot: vi.fn(),
      readCurrentMasterPlot: vi.fn().mockResolvedValue({
        id: "mp_20260321_ab12cd",
        title: "The Last Sky Choir",
        logline: "A disgraced pilot chases a cosmic song to save her flooded home.",
        synopsis:
          "A fallen courier hears a comet sing and discovers the drowned city can still be lifted.",
        mainCharacters: ["Rin", "Ivo"],
        coreConflict:
          "Rin must choose between private escape and saving the city that exiled her.",
        emotionalArc: "She moves from bitterness to sacrificial hope.",
        endingBeat: "Rin turns the comet's music into a rising tide of light.",
        targetDurationSec: 480,
        sourceTaskId: "task_master_plot",
        updatedAt: "2026-03-21T11:58:00.000Z",
        approvedAt: "2026-03-21T11:59:00.000Z",
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn().mockResolvedValue({
        id: "char_batch_20260321_ab12cd",
        projectId: "proj_20260321_ab12cd",
        projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
        sourceMasterPlotId: "mp_20260321_ab12cd",
        characterCount: 2,
        storageDir: "projects/proj_20260321_ab12cd-my-story/character-sheets/batches/char_batch_20260321_ab12cd",
        manifestRelPath:
          "character-sheets/batches/char_batch_20260321_ab12cd/manifest.json",
        createdAt: "2026-03-21T11:59:00.000Z",
        updatedAt: "2026-03-21T12:00:00.000Z",
      }),
      listCharactersByBatchId: vi.fn().mockResolvedValue([
        {
          id: "char_rin_1",
          projectId: "proj_20260321_ab12cd",
          projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
          batchId: "char_batch_20260321_ab12cd",
          sourceMasterPlotId: "mp_20260321_ab12cd",
          characterName: "Rin",
          promptTextGenerated: "Rin generated prompt",
          promptTextCurrent: "Rin current prompt",
          imageAssetPath:
            "character-sheets/batches/char_batch_20260321_ab12cd/characters/char_rin_1/current.png",
          imageWidth: 1536,
          imageHeight: 1024,
          provider: "turnaround-image",
          model: "seedream",
          referenceImages: [],
          status: "approved" as const,
          updatedAt: "2026-03-21T12:00:00.000Z",
          approvedAt: "2026-03-21T12:01:00.000Z",
          sourceTaskId: "task_char_rin_1",
          storageDir: "",
          currentImageRelPath: "",
          currentMetadataRelPath: "",
          promptGeneratedRelPath: "",
          promptCurrentRelPath: "",
          promptVariablesRelPath: "",
          imagePromptRelPath: "",
          versionsStorageDir: "",
        },
        {
          id: "char_ivo_1",
          projectId: "proj_20260321_ab12cd",
          projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
          batchId: "char_batch_20260321_ab12cd",
          sourceMasterPlotId: "mp_20260321_ab12cd",
          characterName: "Ivo",
          promptTextGenerated: "Ivo generated prompt",
          promptTextCurrent: "Ivo current prompt",
          imageAssetPath:
            "character-sheets/batches/char_batch_20260321_ab12cd/characters/char_ivo_1/current.png",
          imageWidth: 1536,
          imageHeight: 1024,
          provider: "turnaround-image",
          model: "seedream",
          referenceImages: [],
          status: "approved" as const,
          updatedAt: "2026-03-21T12:00:00.000Z",
          approvedAt: "2026-03-21T12:01:00.000Z",
          sourceTaskId: "task_char_ivo_1",
          storageDir: "",
          currentImageRelPath: "",
          currentMetadataRelPath: "",
          promptGeneratedRelPath: "",
          promptCurrentRelPath: "",
          promptVariablesRelPath: "",
          imagePromptRelPath: "",
          versionsStorageDir: "",
        },
      ]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };

    const useCase = createCreateSceneSheetsGenerateTaskUseCase({
      projectRepository,
      masterPlotStorage,
      characterSheetRepository,
      taskRepository,
      taskFileStorage,
      taskQueue,
      taskIdGenerator: {
        generateTaskId: () => "task_20260321_scene_sheets",
      },
      clock: {
        now: () => "2026-03-21T12:00:00.000Z",
      },
    });

    const result = await useCase.execute({ projectId: "proj_20260321_ab12cd" });

    expect(taskRepository.insert).toHaveBeenCalledWith(
      expect.objectContaining({
        id: "task_20260321_scene_sheets",
        projectId: "proj_20260321_ab12cd",
        type: "scene_sheets_generate",
        status: "pending",
      }),
    );
    expect(taskFileStorage.createTaskArtifacts).toHaveBeenCalledWith({
      task: expect.objectContaining({ id: "task_20260321_scene_sheets" }),
      input: {
        taskId: "task_20260321_scene_sheets",
        projectId: "proj_20260321_ab12cd",
        taskType: "scene_sheets_generate",
        batchId: "scene_batch_task_20260321_scene_sheets",
        sourceMasterPlotId: "mp_20260321_ab12cd",
        sourceCharacterSheetBatchId: "char_batch_20260321_ab12cd",
      },
    });
    expect(taskQueue.enqueue).toHaveBeenCalledWith({
      taskId: "task_20260321_scene_sheets",
      queueName: "scene-sheets-generate",
      taskType: "scene_sheets_generate",
    });
    expect(projectRepository.updateStatus).toHaveBeenCalledWith({
      projectId: "proj_20260321_ab12cd",
      status: "scene_sheets_generating",
      updatedAt: "2026-03-21T12:00:00.000Z",
    });
    expect(result.type).toBe("scene_sheets_generate");
  });

  it("throws when the project does not exist", async () => {
    const useCase = createCreateSceneSheetsGenerateTaskUseCase({
      projectRepository: {
        insert: vi.fn(),
        findById: vi.fn().mockResolvedValue(null),
        updatePremiseMetadata: vi.fn(),
        updateCurrentMasterPlot: vi.fn(),
        updateCurrentCharacterSheetBatch: vi.fn(),
        updateCurrentSceneSheetBatch: vi.fn(),
        updateCurrentStoryboard: vi.fn(),
        updateCurrentShotScript: vi.fn(),
        updateCurrentImageBatch: vi.fn(),
        updateCurrentVideoBatch: vi.fn(),
        updateStatus: vi.fn(),
        listAll: vi.fn(),
      },
      masterPlotStorage: {
        initializePromptTemplate: vi.fn(),
        readPromptTemplate: vi.fn(),
        writePromptSnapshot: vi.fn(),
        writeRawResponse: vi.fn(),
        writeCurrentMasterPlot: vi.fn(),
        readCurrentMasterPlot: vi.fn(),
      },
      characterSheetRepository: {
        insertBatch: vi.fn(),
        findBatchById: vi.fn().mockResolvedValue({
          id: "char_batch_20260321_ab12cd",
          projectId: "proj_20260321_ab12cd",
          projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
          sourceMasterPlotId: "mp_20260321_ab12cd",
          characterCount: 1,
          storageDir: "projects/proj_20260321_ab12cd-my-story/character-sheets/batches/char_batch_20260321_ab12cd",
          manifestRelPath:
            "character-sheets/batches/char_batch_20260321_ab12cd/manifest.json",
          createdAt: "2026-03-21T11:59:00.000Z",
          updatedAt: "2026-03-21T12:00:00.000Z",
        }),
        listCharactersByBatchId: vi.fn().mockResolvedValue([
          {
            id: "char_rin_pending",
            projectId: "proj_20260321_ab12cd",
            projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
            batchId: "char_batch_20260321_ab12cd",
            sourceMasterPlotId: "mp_20260321_ab12cd",
            characterName: "Rin",
            promptTextGenerated: "Rin generated prompt",
            promptTextCurrent: "Rin current prompt",
            imageAssetPath: "character-sheets/char_rin_pending/current.png",
            imageWidth: 1536,
            imageHeight: 1024,
            provider: "turnaround-image",
            model: "seedream",
            referenceImages: [],
            status: "in_review" as const,
            updatedAt: "2026-03-21T12:00:00.000Z",
            approvedAt: null,
            sourceTaskId: "task_char_rin_pending",
            storageDir: "",
            currentImageRelPath: "",
            currentMetadataRelPath: "",
            promptGeneratedRelPath: "",
            promptCurrentRelPath: "",
            promptVariablesRelPath: "",
            imagePromptRelPath: "",
            versionsStorageDir: "",
          },
        ]),
        insertCharacter: vi.fn(),
        findCharacterById: vi.fn(),
        updateCharacter: vi.fn(),
      },
      taskRepository: {
        insert: vi.fn(),
        findById: vi.fn(),
        findLatestByProjectId: vi.fn(),
        delete: vi.fn(),
        markRunning: vi.fn(),
        markSucceeded: vi.fn(),
        markFailed: vi.fn(),
      },
      taskFileStorage: {
        createTaskArtifacts: vi.fn(),
        readTaskInput: vi.fn(),
        writeTaskOutput: vi.fn(),
        appendTaskLog: vi.fn(),
      },
      taskQueue: { enqueue: vi.fn() },
      taskIdGenerator: { generateTaskId: () => "task_20260321_scene_sheets" },
      clock: { now: () => "2026-03-21T12:00:00.000Z" },
    });

    await expect(useCase.execute({ projectId: "missing-project" })).rejects.toBeInstanceOf(
      ProjectNotFoundError,
    );
  });

  it("allows scene-sheet regeneration after the project has already entered the scene-sheets stage", async () => {
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_20260321_ab12cd",
        name: "My Story",
        slug: "my-story",
        storageDir: "projects/proj_20260321_ab12cd-my-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "mp_20260321_ab12cd",
        currentCharacterSheetBatchId: "char_batch_20260321_ab12cd",
        currentSceneSheetBatchId: "scene_batch_existing",
        currentStoryboardId: null,
        currentShotScriptId: null,
        currentImageBatchId: null,
        currentVideoBatchId: null,
        status: "scene_sheets_in_review",
        createdAt: "2026-03-21T11:59:00.000Z",
        updatedAt: "2026-03-21T12:00:00.000Z",
        premiseUpdatedAt: "2026-03-21T12:00:00.000Z",
        visualStyleText: "赛璐璐动画，潮湿冷蓝夜景",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentSceneSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateCurrentVideoBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn(),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn(),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const taskQueue = {
      enqueue: vi.fn(),
    };
    const masterPlotStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeCurrentMasterPlot: vi.fn(),
      readCurrentMasterPlot: vi.fn().mockResolvedValue({
        id: "mp_20260321_ab12cd",
        title: "The Last Sky Choir",
        logline: "A disgraced pilot chases a cosmic song to save her flooded home.",
        synopsis:
          "A fallen courier hears a comet sing and discovers the drowned city can still be lifted.",
        mainCharacters: ["Rin", "Ivo"],
        coreConflict:
          "Rin must choose between private escape and saving the city that exiled her.",
        emotionalArc: "She moves from bitterness to sacrificial hope.",
        endingBeat: "Rin turns the comet's music into a rising tide of light.",
        targetDurationSec: 480,
        sourceTaskId: "task_master_plot",
        updatedAt: "2026-03-21T11:58:00.000Z",
        approvedAt: "2026-03-21T11:59:00.000Z",
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn().mockResolvedValue({
        id: "char_batch_20260321_ab12cd",
        projectId: "proj_20260321_ab12cd",
        projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
        sourceMasterPlotId: "mp_20260321_ab12cd",
        characterCount: 2,
        storageDir: "projects/proj_20260321_ab12cd-my-story/character-sheets/batches/char_batch_20260321_ab12cd",
        manifestRelPath:
          "character-sheets/batches/char_batch_20260321_ab12cd/manifest.json",
        createdAt: "2026-03-21T11:59:00.000Z",
        updatedAt: "2026-03-21T12:00:00.000Z",
      }),
      listCharactersByBatchId: vi.fn().mockResolvedValue([
        {
          id: "char_rin_1",
          projectId: "proj_20260321_ab12cd",
          projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
          batchId: "char_batch_20260321_ab12cd",
          sourceMasterPlotId: "mp_20260321_ab12cd",
          characterName: "Rin",
          promptTextGenerated: "Rin generated prompt",
          promptTextCurrent: "Rin current prompt",
          imageAssetPath:
            "character-sheets/batches/char_batch_20260321_ab12cd/characters/char_rin_1/current.png",
          imageWidth: 1536,
          imageHeight: 1024,
          provider: "turnaround-image",
          model: "seedream",
          referenceImages: [],
          status: "approved" as const,
          updatedAt: "2026-03-21T12:00:00.000Z",
          approvedAt: "2026-03-21T12:01:00.000Z",
          sourceTaskId: "task_char_rin_1",
          storageDir: "",
          currentImageRelPath: "",
          currentMetadataRelPath: "",
          promptGeneratedRelPath: "",
          promptCurrentRelPath: "",
          promptVariablesRelPath: "",
          imagePromptRelPath: "",
          versionsStorageDir: "",
        },
        {
          id: "char_ivo_1",
          projectId: "proj_20260321_ab12cd",
          projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
          batchId: "char_batch_20260321_ab12cd",
          sourceMasterPlotId: "mp_20260321_ab12cd",
          characterName: "Ivo",
          promptTextGenerated: "Ivo generated prompt",
          promptTextCurrent: "Ivo current prompt",
          imageAssetPath:
            "character-sheets/batches/char_batch_20260321_ab12cd/characters/char_ivo_1/current.png",
          imageWidth: 1536,
          imageHeight: 1024,
          provider: "turnaround-image",
          model: "seedream",
          referenceImages: [],
          status: "approved" as const,
          updatedAt: "2026-03-21T12:00:00.000Z",
          approvedAt: "2026-03-21T12:01:00.000Z",
          sourceTaskId: "task_char_ivo_1",
          storageDir: "",
          currentImageRelPath: "",
          currentMetadataRelPath: "",
          promptGeneratedRelPath: "",
          promptCurrentRelPath: "",
          promptVariablesRelPath: "",
          imagePromptRelPath: "",
          versionsStorageDir: "",
        },
      ]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };

    const useCase = createCreateSceneSheetsGenerateTaskUseCase({
      projectRepository,
      masterPlotStorage,
      characterSheetRepository,
      taskRepository,
      taskFileStorage,
      taskQueue,
      taskIdGenerator: {
        generateTaskId: () => "task_20260321_scene_sheets_rerun",
      },
      clock: {
        now: () => "2026-03-21T12:00:00.000Z",
      },
    });

    const result = await useCase.execute({ projectId: "proj_20260321_ab12cd" });

    expect(taskQueue.enqueue).toHaveBeenCalledWith({
      taskId: "task_20260321_scene_sheets_rerun",
      queueName: "scene-sheets-generate",
      taskType: "scene_sheets_generate",
    });
    expect(projectRepository.updateStatus).toHaveBeenCalledWith({
      projectId: "proj_20260321_ab12cd",
      status: "scene_sheets_generating",
      updatedAt: "2026-03-21T12:00:00.000Z",
    });
    expect(result.id).toBe("task_20260321_scene_sheets_rerun");
  });

  it("throws when the project is not ready for scene sheets", async () => {
    const useCase = createCreateSceneSheetsGenerateTaskUseCase({
      projectRepository: {
        insert: vi.fn(),
        findById: vi.fn().mockResolvedValue({
          id: "proj_20260321_ab12cd",
          name: "My Story",
          slug: "my-story",
          storageDir: "projects/proj_20260321_ab12cd-my-story",
          premiseRelPath: "premise/v1.md",
          premiseBytes: 88,
          currentMasterPlotId: "mp_20260321_ab12cd",
          currentCharacterSheetBatchId: "char_batch_20260321_ab12cd",
          currentSceneSheetBatchId: null,
          currentStoryboardId: null,
          currentShotScriptId: null,
          currentImageBatchId: null,
          currentVideoBatchId: null,
          status: "character_sheets_in_review",
          createdAt: "2026-03-21T11:59:00.000Z",
          updatedAt: "2026-03-21T12:00:00.000Z",
          premiseUpdatedAt: "2026-03-21T12:00:00.000Z",
          visualStyleText: "",
        }),
        updatePremiseMetadata: vi.fn(),
        updateCurrentMasterPlot: vi.fn(),
        updateCurrentCharacterSheetBatch: vi.fn(),
        updateCurrentSceneSheetBatch: vi.fn(),
        updateCurrentStoryboard: vi.fn(),
        updateCurrentShotScript: vi.fn(),
        updateCurrentImageBatch: vi.fn(),
        updateCurrentVideoBatch: vi.fn(),
        updateStatus: vi.fn(),
        listAll: vi.fn(),
      },
      masterPlotStorage: {
        initializePromptTemplate: vi.fn(),
        readPromptTemplate: vi.fn(),
        writePromptSnapshot: vi.fn(),
        writeRawResponse: vi.fn(),
        writeCurrentMasterPlot: vi.fn(),
        readCurrentMasterPlot: vi.fn(),
      },
      characterSheetRepository: {
        insertBatch: vi.fn(),
        findBatchById: vi.fn().mockResolvedValue({
          id: "char_batch_20260321_ab12cd",
          projectId: "proj_20260321_ab12cd",
          projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
          sourceMasterPlotId: "mp_20260321_ab12cd",
          characterCount: 1,
          storageDir: "projects/proj_20260321_ab12cd-my-story/character-sheets/batches/char_batch_20260321_ab12cd",
          manifestRelPath:
            "character-sheets/batches/char_batch_20260321_ab12cd/manifest.json",
          createdAt: "2026-03-21T11:59:00.000Z",
          updatedAt: "2026-03-21T12:00:00.000Z",
        }),
        listCharactersByBatchId: vi.fn().mockResolvedValue([
          {
            id: "char_rin_pending",
            projectId: "proj_20260321_ab12cd",
            projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
            batchId: "char_batch_20260321_ab12cd",
            sourceMasterPlotId: "mp_20260321_ab12cd",
            characterName: "Rin",
            promptTextGenerated: "Rin generated prompt",
            promptTextCurrent: "Rin current prompt",
            imageAssetPath: "character-sheets/char_rin_pending/current.png",
            imageWidth: 1536,
            imageHeight: 1024,
            provider: "turnaround-image",
            model: "seedream",
            referenceImages: [],
            status: "in_review" as const,
            updatedAt: "2026-03-21T12:00:00.000Z",
            approvedAt: null,
            sourceTaskId: "task_char_rin_pending",
            storageDir: "",
            currentImageRelPath: "",
            currentMetadataRelPath: "",
            promptGeneratedRelPath: "",
            promptCurrentRelPath: "",
            promptVariablesRelPath: "",
            imagePromptRelPath: "",
            versionsStorageDir: "",
          },
        ]),
        insertCharacter: vi.fn(),
        findCharacterById: vi.fn(),
        updateCharacter: vi.fn(),
      },
      taskRepository: {
        insert: vi.fn(),
        findById: vi.fn(),
        findLatestByProjectId: vi.fn(),
        delete: vi.fn(),
        markRunning: vi.fn(),
        markSucceeded: vi.fn(),
        markFailed: vi.fn(),
      },
      taskFileStorage: {
        createTaskArtifacts: vi.fn(),
        readTaskInput: vi.fn(),
        writeTaskOutput: vi.fn(),
        appendTaskLog: vi.fn(),
      },
      taskQueue: { enqueue: vi.fn() },
      taskIdGenerator: { generateTaskId: () => "task_20260321_scene_sheets" },
      clock: { now: () => "2026-03-21T12:00:00.000Z" },
    });

    await expect(
      useCase.execute({ projectId: "proj_20260321_ab12cd" }),
    ).rejects.toBeInstanceOf(ProjectValidationError);
  });

  it("throws when the approved current master plot is missing", async () => {
    const useCase = createCreateSceneSheetsGenerateTaskUseCase({
      projectRepository: {
        insert: vi.fn(),
        findById: vi.fn().mockResolvedValue({
          id: "proj_20260321_ab12cd",
          name: "My Story",
          slug: "my-story",
          storageDir: "projects/proj_20260321_ab12cd-my-story",
          premiseRelPath: "premise/v1.md",
          premiseBytes: 88,
          currentMasterPlotId: "mp_20260321_ab12cd",
          currentCharacterSheetBatchId: "char_batch_20260321_ab12cd",
          currentSceneSheetBatchId: null,
          currentStoryboardId: null,
          currentShotScriptId: null,
          currentImageBatchId: null,
          currentVideoBatchId: null,
          status: "character_sheets_approved",
          createdAt: "2026-03-21T11:59:00.000Z",
          updatedAt: "2026-03-21T12:00:00.000Z",
          premiseUpdatedAt: "2026-03-21T12:00:00.000Z",
          visualStyleText: "",
        }),
        updatePremiseMetadata: vi.fn(),
        updateCurrentMasterPlot: vi.fn(),
        updateCurrentCharacterSheetBatch: vi.fn(),
        updateCurrentSceneSheetBatch: vi.fn(),
        updateCurrentStoryboard: vi.fn(),
        updateCurrentShotScript: vi.fn(),
        updateCurrentImageBatch: vi.fn(),
        updateCurrentVideoBatch: vi.fn(),
        updateStatus: vi.fn(),
        listAll: vi.fn(),
      },
      masterPlotStorage: {
        initializePromptTemplate: vi.fn(),
        readPromptTemplate: vi.fn(),
        writePromptSnapshot: vi.fn(),
        writeRawResponse: vi.fn(),
        writeCurrentMasterPlot: vi.fn(),
        readCurrentMasterPlot: vi.fn().mockResolvedValue(null),
      },
      characterSheetRepository: {
        insertBatch: vi.fn(),
        findBatchById: vi.fn().mockResolvedValue({
          id: "char_batch_20260321_ab12cd",
          projectId: "proj_20260321_ab12cd",
          projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
          sourceMasterPlotId: "mp_20260321_ab12cd",
          characterCount: 1,
          storageDir: "projects/proj_20260321_ab12cd-my-story/character-sheets/batches/char_batch_20260321_ab12cd",
          manifestRelPath:
            "character-sheets/batches/char_batch_20260321_ab12cd/manifest.json",
          createdAt: "2026-03-21T11:59:00.000Z",
          updatedAt: "2026-03-21T12:00:00.000Z",
        }),
        listCharactersByBatchId: vi.fn().mockResolvedValue([
          {
            id: "char_rin_approved",
            projectId: "proj_20260321_ab12cd",
            projectStorageDir: "projects/proj_20260321_ab12cd-my-story",
            batchId: "char_batch_20260321_ab12cd",
            sourceMasterPlotId: "mp_20260321_ab12cd",
            characterName: "Rin",
            promptTextGenerated: "Rin generated prompt",
            promptTextCurrent: "Rin current prompt",
            imageAssetPath: "character-sheets/char_rin_approved/current.png",
            imageWidth: 1536,
            imageHeight: 1024,
            provider: "turnaround-image",
            model: "seedream",
            referenceImages: [],
            status: "approved" as const,
            updatedAt: "2026-03-21T12:00:00.000Z",
            approvedAt: "2026-03-21T12:01:00.000Z",
            sourceTaskId: "task_char_rin_approved",
            storageDir: "",
            currentImageRelPath: "",
            currentMetadataRelPath: "",
            promptGeneratedRelPath: "",
            promptCurrentRelPath: "",
            promptVariablesRelPath: "",
            imagePromptRelPath: "",
            versionsStorageDir: "",
          },
        ]),
        insertCharacter: vi.fn(),
        findCharacterById: vi.fn(),
        updateCharacter: vi.fn(),
      },
      taskRepository: {
        insert: vi.fn(),
        findById: vi.fn(),
        findLatestByProjectId: vi.fn(),
        delete: vi.fn(),
        markRunning: vi.fn(),
        markSucceeded: vi.fn(),
        markFailed: vi.fn(),
      },
      taskFileStorage: {
        createTaskArtifacts: vi.fn(),
        readTaskInput: vi.fn(),
        writeTaskOutput: vi.fn(),
        appendTaskLog: vi.fn(),
      },
      taskQueue: { enqueue: vi.fn() },
      taskIdGenerator: { generateTaskId: () => "task_20260321_scene_sheets" },
      clock: { now: () => "2026-03-21T12:00:00.000Z" },
    });

    await expect(
      useCase.execute({ projectId: "proj_20260321_ab12cd" }),
    ).rejects.toBeInstanceOf(CurrentMasterPlotNotFoundError);
  });
});
