import { describe, expect, it, vi } from "vitest";

import { createGetVideoUseCase } from "../src/index";

describe("get video use case", () => {
  it("repairs empty prompts before returning a current video shot", async () => {
    const videoRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listSegmentsByBatchId: vi.fn(),
      insertSegment: vi.fn(),
      findSegmentById: vi.fn().mockResolvedValue({
        id: "video_shot_1",
        batchId: "video_batch_1",
        projectId: "proj_1",
        projectStorageDir: "projects/proj_1-my-story",
        sourceImageBatchId: "image_batch_1",
        sourceShotScriptId: "shot_script_1",
        shotId: "shot_1",
        shotCode: "SC01-SG01-SH01",
        sceneId: "scene_1",
        segmentId: "segment_1",
        shotOrder: 1,
        frameDependency: "start_frame_only",
        status: "failed",
        promptTextSeed: "",
        promptTextCurrent: "",
        promptUpdatedAt: "",
        videoAssetPath: null,
        thumbnailAssetPath: null,
        durationSec: 3,
        provider: null,
        model: null,
        approvedAt: null,
        updatedAt: "2026-03-25T00:18:00.000Z",
        sourceTaskId: null,
        storageDir: "ignored",
        currentVideoRelPath: "ignored",
        currentMetadataRelPath: "ignored",
        thumbnailRelPath: "ignored",
        versionsStorageDir: "ignored",
      }),
      findCurrentSegmentByProjectIdAndSegmentId: vi.fn(),
      findCurrentSegmentByProjectIdAndSceneIdAndSegmentId: vi.fn(),
      updateSegment: vi.fn(),
    };

    const useCase = createGetVideoUseCase({
      projectRepository: {
        insert: vi.fn(),
        findById: vi.fn().mockResolvedValue({
          id: "proj_1",
          storageDir: "projects/proj_1-my-story",
          currentVideoBatchId: "video_batch_1",
        }),
        listAll: vi.fn(),
        updatePremiseMetadata: vi.fn(),
        updateCurrentMasterPlot: vi.fn(),
        updateCurrentCharacterSheetBatch: vi.fn(),
        updateCurrentStoryboard: vi.fn(),
        updateCurrentShotScript: vi.fn(),
        updateCurrentImageBatch: vi.fn(),
        updateCurrentVideoBatch: vi.fn(),
        updateStatus: vi.fn(),
      },
      shotScriptStorage: {
        initializePromptTemplate: vi.fn(),
        readPromptTemplate: vi.fn(),
        writePromptSnapshot: vi.fn(),
        writeRawResponse: vi.fn(),
        writeShotScriptVersion: vi.fn(),
        readShotScriptVersion: vi.fn(),
        writeCurrentShotScript: vi.fn(),
        readCurrentShotScript: vi.fn().mockResolvedValue({
          id: "shot_script_1",
          title: "Episode 1",
          sourceStoryboardId: "storyboard_1",
          sourceTaskId: "task_shot_script_1",
          updatedAt: "2026-03-25T00:17:00.000Z",
          approvedAt: "2026-03-25T00:18:00.000Z",
          segmentCount: 1,
          shotCount: 2,
          totalDurationSec: 8,
          segments: [
            {
              segmentId: "segment_1",
              sceneId: "scene_1",
              order: 1,
              name: "Arrival",
              summary: "Rin arrives at the flooded market.",
              durationSec: 8,
              status: "approved",
              lastGeneratedAt: "2026-03-25T00:17:00.000Z",
              approvedAt: "2026-03-25T00:18:00.000Z",
              shots: [
                {
                  id: "shot_1",
                  sceneId: "scene_1",
                  segmentId: "segment_1",
                  order: 1,
                  shotCode: "SC01-SG01-SH01",
                  durationSec: 3,
                  frameDependency: "start_frame_only",
                  purpose: "Arrival",
                  visual: "Rin enters the market.",
                  subject: "Rin",
                  action: "Rin steps into the flooded market and looks ahead.",
                  dialogue: null,
                  os: null,
                  audio: null,
                  transitionHint: null,
                  continuityNotes: null,
                },
                {
                  id: "shot_2",
                  sceneId: "scene_1",
                  segmentId: "segment_1",
                  order: 2,
                  shotCode: "SC01-SG01-SH02",
                  durationSec: 5,
                  frameDependency: "start_and_end_frame",
                  purpose: "Discovery",
                  visual: "Rin spots the route forward.",
                  subject: "Rin",
                  action: "Rin points toward the brighter alley beyond the stalls.",
                  dialogue: null,
                  os: null,
                  audio: null,
                  transitionHint: null,
                  continuityNotes: null,
                },
              ],
            },
          ],
        }),
      },
      shotImageRepository: {
        insertBatch: vi.fn(),
        findBatchById: vi.fn(),
        findCurrentBatchByProjectId: vi.fn(),
        listFramesByBatchId: vi.fn(),
        listShotsByBatchId: vi.fn().mockResolvedValue([
          {
            id: "shot_ref_1",
            batchId: "image_batch_1",
            projectId: "proj_1",
            sourceShotScriptId: "shot_script_1",
            sceneId: "scene_1",
            segmentId: "segment_1",
            shotId: "shot_1",
            storageDir: "ignored",
            manifestRelPath: "ignored",
            updatedAt: "2026-03-25T00:18:00.000Z",
            startFrame: {
              id: "frame_start_1",
              promptTextSeed: "seed",
              promptTextCurrent: "current",
              imageAssetPath: "images/start.png",
              imageWidth: 1024,
              imageHeight: 576,
              provider: null,
              model: null,
              updatedAt: "2026-03-25T00:18:00.000Z",
              currentImageRelPath: "ignored",
              currentMetadataRelPath: "ignored",
              promptSeedRelPath: "ignored",
              promptCurrentRelPath: "ignored",
              planningRelPath: "ignored",
              versionsStorageDir: "ignored",
              promptVersionsStorageDir: "ignored",
            },
            endFrame: null,
          },
        ]),
        insertFrame: vi.fn(),
        findFrameById: vi.fn(),
        updateFrame: vi.fn(),
      },
      videoStorage: {
        initializePromptTemplate: vi.fn(),
        readPromptTemplate: vi.fn(),
        writePromptSnapshot: vi.fn(),
        writePromptPlan: vi.fn(),
        writeRawResponse: vi.fn(),
        writeBatchManifest: vi.fn(),
        writeCurrentVideo: vi.fn(),
        writeVideoVersion: vi.fn(),
        resolveProjectAssetPath: vi.fn(),
      },
      videoPromptProvider: {
        generateVideoPrompt: vi.fn().mockResolvedValue({
          finalPrompt:
            "以<<<image_1>>>为首帧锚点，林进入积水市场并短暂停步，口型不可见，无对白，保留雨声与脚步踩水声。",
          dialoguePlan: "无明确台词。",
          audioPlan: "雨声与脚步踩水声。",
          visualGuardrails: "保持林的外观与服装稳定。",
          rationale: "修复缺失提示词时仍保留环境声与动作。",
          provider: "gemini",
          model: "gemini-3.1-pro-preview",
        }),
      },
      videoRepository,
    });

    const result = await useCase.execute({
      projectId: "proj_1",
      videoId: "video_shot_1",
    });

    expect(videoRepository.updateSegment).toHaveBeenCalledWith(
      expect.objectContaining({
        id: "video_shot_1",
        promptTextSeed:
          "以<<<image_1>>>为首帧锚点，林进入积水市场并短暂停步，口型不可见，无对白，保留雨声与脚步踩水声。",
        promptTextCurrent:
          "以<<<image_1>>>为首帧锚点，林进入积水市场并短暂停步，口型不可见，无对白，保留雨声与脚步踩水声。",
      }),
    );
    expect(result.promptTextSeed).toBe(
      "以<<<image_1>>>为首帧锚点，林进入积水市场并短暂停步，口型不可见，无对白，保留雨声与脚步踩水声。",
    );
    expect(result.promptTextCurrent).toBe(
      "以<<<image_1>>>为首帧锚点，林进入积水市场并短暂停步，口型不可见，无对白，保留雨声与脚步踩水声。",
    );
  });

  it("returns the original shot when prompt repair is blocked by the provider", async () => {
    const blockedSegment = {
      id: "video_shot_1",
      batchId: "video_batch_1",
      projectId: "proj_1",
      projectStorageDir: "projects/proj_1-my-story",
      sourceImageBatchId: "image_batch_1",
      sourceShotScriptId: "shot_script_1",
      shotId: "shot_1",
      shotCode: "SC01-SG01-SH01",
      sceneId: "scene_1",
      segmentId: "segment_1",
      shotOrder: 1,
      frameDependency: "start_frame_only" as const,
      status: "failed" as const,
      promptTextSeed: "",
      promptTextCurrent: "",
      promptUpdatedAt: "",
      videoAssetPath: null,
      thumbnailAssetPath: null,
      durationSec: 3,
      provider: null,
      model: null,
      approvedAt: null,
      updatedAt: "2026-03-25T00:18:00.000Z",
      sourceTaskId: null,
      storageDir: "ignored",
      currentVideoRelPath: "ignored",
      currentMetadataRelPath: "ignored",
      thumbnailRelPath: "ignored",
      versionsStorageDir: "ignored",
    };
    const videoRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listSegmentsByBatchId: vi.fn(),
      insertSegment: vi.fn(),
      findSegmentById: vi.fn().mockResolvedValue(blockedSegment),
      findCurrentSegmentByProjectIdAndSegmentId: vi.fn(),
      findCurrentSegmentByProjectIdAndSceneIdAndSegmentId: vi.fn(),
      updateSegment: vi.fn(),
    };
    const useCase = createGetVideoUseCase({
      projectRepository: {
        insert: vi.fn(),
        findById: vi.fn().mockResolvedValue({
          id: "proj_1",
          storageDir: "projects/proj_1-my-story",
          currentVideoBatchId: "video_batch_1",
        }),
        listAll: vi.fn(),
        updatePremiseMetadata: vi.fn(),
        updateCurrentMasterPlot: vi.fn(),
        updateCurrentCharacterSheetBatch: vi.fn(),
        updateCurrentStoryboard: vi.fn(),
        updateCurrentShotScript: vi.fn(),
        updateCurrentImageBatch: vi.fn(),
        updateCurrentVideoBatch: vi.fn(),
        updateStatus: vi.fn(),
      },
      shotScriptStorage: {
        initializePromptTemplate: vi.fn(),
        readPromptTemplate: vi.fn(),
        writePromptSnapshot: vi.fn(),
        writeRawResponse: vi.fn(),
        writeShotScriptVersion: vi.fn(),
        readShotScriptVersion: vi.fn(),
        writeCurrentShotScript: vi.fn(),
        readCurrentShotScript: vi.fn().mockResolvedValue({
          id: "shot_script_1",
          title: "Episode 1",
          sourceStoryboardId: "storyboard_1",
          sourceTaskId: "task_shot_script_1",
          updatedAt: "2026-03-25T00:17:00.000Z",
          approvedAt: "2026-03-25T00:18:00.000Z",
          segmentCount: 1,
          shotCount: 1,
          totalDurationSec: 3,
          segments: [
            {
              segmentId: "segment_1",
              sceneId: "scene_1",
              order: 1,
              name: "Arrival",
              summary: "Rin arrives at the flooded market.",
              durationSec: 3,
              status: "approved",
              lastGeneratedAt: "2026-03-25T00:17:00.000Z",
              approvedAt: "2026-03-25T00:18:00.000Z",
              shots: [
                {
                  id: "shot_1",
                  sceneId: "scene_1",
                  segmentId: "segment_1",
                  order: 1,
                  shotCode: "SC01-SG01-SH01",
                  durationSec: 3,
                  frameDependency: "start_frame_only",
                  purpose: "Arrival",
                  visual: "Rin enters the market.",
                  subject: "Rin",
                  action: "Rin steps into the flooded market and looks ahead.",
                  dialogue: null,
                  os: null,
                  audio: null,
                  transitionHint: null,
                  continuityNotes: null,
                },
              ],
            },
          ],
        }),
      },
      shotImageRepository: {
        insertBatch: vi.fn(),
        findBatchById: vi.fn(),
        findCurrentBatchByProjectId: vi.fn(),
        listFramesByBatchId: vi.fn(),
        listShotsByBatchId: vi.fn().mockResolvedValue([
          {
            id: "shot_ref_1",
            batchId: "image_batch_1",
            projectId: "proj_1",
            sourceShotScriptId: "shot_script_1",
            sceneId: "scene_1",
            segmentId: "segment_1",
            shotId: "shot_1",
            storageDir: "ignored",
            manifestRelPath: "ignored",
            updatedAt: "2026-03-25T00:18:00.000Z",
            startFrame: {
              id: "frame_start_1",
              promptTextSeed: "seed",
              promptTextCurrent: "current",
              imageAssetPath: "images/start.png",
              imageWidth: 1024,
              imageHeight: 576,
              provider: null,
              model: null,
              updatedAt: "2026-03-25T00:18:00.000Z",
              currentImageRelPath: "ignored",
              currentMetadataRelPath: "ignored",
              promptSeedRelPath: "ignored",
              promptCurrentRelPath: "ignored",
              planningRelPath: "ignored",
              versionsStorageDir: "ignored",
              promptVersionsStorageDir: "ignored",
            },
            endFrame: null,
          },
        ]),
        insertFrame: vi.fn(),
        findFrameById: vi.fn(),
        updateFrame: vi.fn(),
      },
      videoStorage: {
        initializePromptTemplate: vi.fn(),
        readPromptTemplate: vi.fn(),
        writePromptSnapshot: vi.fn(),
        writePromptPlan: vi.fn(),
        writeRawResponse: vi.fn(),
        writeBatchManifest: vi.fn(),
        writeCurrentVideo: vi.fn(),
        writeVideoVersion: vi.fn(),
        resolveProjectAssetPath: vi.fn(),
      },
      videoPromptProvider: {
        generateVideoPrompt: vi
          .fn()
          .mockRejectedValue(
            new Error(
              "Gemini video prompt provider request failed with status 500; code=request_body_blocked; message=request blocked by Google Gemini (PROHIBITED_CONTENT)",
            ),
          ),
      },
      videoRepository,
    });

    const result = await useCase.execute({
      projectId: "proj_1",
      videoId: "video_shot_1",
    });

    expect(videoRepository.updateSegment).not.toHaveBeenCalled();
    expect(result).toEqual(blockedSegment);
  });
});
