import { describe, expect, it, vi } from "vitest";

import {
  createProcessFramePromptGenerateTaskUseCase,
  createShotReferenceRecord,
} from "../src/index";

describe("process frame prompt generate task use case", () => {
  it("filters unknown planner ids, degrades missing reference images, and persists editable prompt fields", async () => {
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "task_frame_prompt_1",
        projectId: "proj_20260324_ab12cd",
        type: "frame_prompt_generate",
        status: "pending",
        queueName: "frame-prompt-generate",
        storageDir: "projects/proj_20260324_ab12cd-my-story/tasks/task_frame_prompt_1",
        inputRelPath: "tasks/task_frame_prompt_1/input.json",
        outputRelPath: "tasks/task_frame_prompt_1/output.json",
        logRelPath: "tasks/task_frame_prompt_1/log.txt",
        errorMessage: null,
        createdAt: "2026-03-24T00:12:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        startedAt: null,
        finishedAt: null,
      }),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_20260324_ab12cd",
        name: "My Story",
        slug: "my-story",
        storageDir: "projects/proj_20260324_ab12cd-my-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "master_plot_v1",
        currentCharacterSheetBatchId: "char_batch_v1",
        currentStoryboardId: "storyboard_v1",
        currentShotScriptId: "shot_script_v1",
        currentImageBatchId: "image_batch_task_20260324_images",
        status: "images_generating",
        createdAt: "2026-03-24T00:00:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        premiseUpdatedAt: "2026-03-24T00:00:00.000Z",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn().mockResolvedValue({
        taskId: "task_frame_prompt_1",
        projectId: "proj_20260324_ab12cd",
        taskType: "frame_prompt_generate",
        batchId: "image_batch_task_20260324_images",
        shotId: "shot_1",
        frameId: "frame_segment_1_start",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_1",
        frameType: "start_frame",
      }),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const shotImageRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listFramesByBatchId: vi.fn(),
      insertFrame: vi.fn(),
      findFrameById: vi.fn().mockResolvedValue({
        id: "frame_segment_1_start",
        batchId: "image_batch_task_20260324_images",
        projectId: "proj_20260324_ab12cd",
        projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_1",
        order: 1,
        frameType: "start_frame",
        planStatus: "pending",
        imageStatus: "pending",
        selectedCharacterIds: [],
        matchedReferenceImagePaths: [],
        unmatchedCharacterIds: [],
        promptTextSeed: "",
        promptTextCurrent: "",
        negativePromptTextCurrent: null,
        promptUpdatedAt: null,
        imageAssetPath: null,
        imageWidth: null,
        imageHeight: null,
        provider: null,
        model: null,
        approvedAt: null,
        updatedAt: "2026-03-24T00:12:00.000Z",
        sourceTaskId: null,
        storageDir:
          "projects/proj_20260324_ab12cd-my-story/images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame",
        planningRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame/planning.json",
        promptSeedRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame/prompt.seed.txt",
        promptCurrentRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame/prompt.current.txt",
        currentImageRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame/current.png",
        currentMetadataRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame/current.json",
        promptVersionsStorageDir:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame/prompt.versions",
        versionsStorageDir:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/start-frame/versions",
      }),
      updateFrame: vi.fn(),
    };
    const shotImageStorage = {
      writeBatchManifest: vi.fn(),
      writeFramePlanning: vi.fn(),
      writeFramePromptFiles: vi.fn(),
      writeFramePromptVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      writeImageVersion: vi.fn(),
      readCurrentFrame: vi.fn(),
      resolveProjectAssetPath: vi.fn(),
    };
    const shotScriptStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeShotScriptVersion: vi.fn(),
      readShotScriptVersion: vi.fn(),
      writeCurrentShotScript: vi.fn(),
      readCurrentShotScript: vi.fn().mockResolvedValue({
        id: "shot_script_v1",
        title: "Episode 1 Shot Script",
        sourceStoryboardId: "storyboard_v1",
        sourceTaskId: "task_shot_script",
        updatedAt: "2026-03-24T00:10:00.000Z",
        approvedAt: "2026-03-24T00:10:00.000Z",
        segmentCount: 1,
        shotCount: 1,
        totalDurationSec: 6,
        segments: [
          {
            segmentId: "segment_1",
            sceneId: "scene_1",
            order: 1,
            name: "集市压境",
            summary: "林夏确认对手已经堵住出口。",
            durationSec: 6,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [
              {
                id: "shot_1",
                sceneId: "scene_1",
                segmentId: "segment_1",
                order: 1,
                shotCode: "S01-SG01-SH01",
                durationSec: 3,
                purpose: "交代堵路。",
                visual: "清晨积水集市入口。",
                subject: "林夏",
                action: "她停住脚步。",
                frameDependency: "start_and_end_frame",
                dialogue: null,
                os: "来得比我还快。",
                audio: "雨声与水声。",
                transitionHint: null,
                continuityNotes: null,
              },
            ],
          },
        ],
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listCharactersByBatchId: vi.fn().mockResolvedValue([
        {
          id: "char_rin",
          projectId: "proj_20260324_ab12cd",
          projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
          batchId: "char_batch_v1",
          sourceMasterPlotId: "master_plot_v1",
          characterName: "林夏",
          promptTextGenerated: "银色飞行夹克",
          promptTextCurrent: "银色飞行夹克，湿透衣角",
          referenceImages: [],
          imageAssetPath:
            "projects/proj_20260324_ab12cd-my-story/character-sheets/char_rin/current.png",
          imageWidth: 1024,
          imageHeight: 1024,
          provider: "vector-engine",
          model: "turnaround-v1",
          status: "approved",
          updatedAt: "2026-03-24T00:08:00.000Z",
          approvedAt: "2026-03-24T00:09:00.000Z",
          sourceTaskId: "task_char_rin",
          storageDir: "ignored",
          currentImageRelPath: "ignored",
          currentMetadataRelPath: "ignored",
          promptGeneratedRelPath: "ignored",
          promptCurrentRelPath: "ignored",
          promptVariablesRelPath: "ignored",
          imagePromptRelPath: "ignored",
          versionsStorageDir: "ignored",
        },
        {
          id: "char_ivo",
          projectId: "proj_20260324_ab12cd",
          projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
          batchId: "char_batch_v1",
          sourceMasterPlotId: "master_plot_v1",
          characterName: "伊沃",
          promptTextGenerated: "机修工围裙",
          promptTextCurrent: "机修工围裙，油污手套",
          referenceImages: [],
          imageAssetPath: null,
          imageWidth: null,
          imageHeight: null,
          provider: null,
          model: null,
          status: "approved",
          updatedAt: "2026-03-24T00:08:00.000Z",
          approvedAt: "2026-03-24T00:09:00.000Z",
          sourceTaskId: "task_char_ivo",
          storageDir: "ignored",
          currentImageRelPath: "ignored",
          currentMetadataRelPath: "ignored",
          promptGeneratedRelPath: "ignored",
          promptCurrentRelPath: "ignored",
          promptVariablesRelPath: "ignored",
          imagePromptRelPath: "ignored",
          versionsStorageDir: "ignored",
        },
        {
          id: "char_unapproved",
          projectId: "proj_20260324_ab12cd",
          projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
          batchId: "char_batch_v1",
          sourceMasterPlotId: "master_plot_v1",
          characterName: "未审批角色",
          promptTextGenerated: "未审批角色",
          promptTextCurrent: "未审批角色",
          referenceImages: [],
          imageAssetPath: null,
          imageWidth: null,
          imageHeight: null,
          provider: null,
          model: null,
          status: "in_review",
          updatedAt: "2026-03-24T00:08:00.000Z",
          approvedAt: null,
          sourceTaskId: "task_char_unapproved",
          storageDir: "ignored",
          currentImageRelPath: "ignored",
          currentMetadataRelPath: "ignored",
          promptGeneratedRelPath: "ignored",
          promptCurrentRelPath: "ignored",
          promptVariablesRelPath: "ignored",
          imagePromptRelPath: "ignored",
          versionsStorageDir: "ignored",
        },
      ]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };
    const characterSheetStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writeBatchManifest: vi.fn(),
      writeGeneratedPrompt: vi.fn(),
      writeImageVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      readCurrentCharacterSheet: vi.fn().mockResolvedValue({
        width: 1024,
        height: 1024,
        provider: "vector-engine",
      }),
      listReferenceImages: vi.fn(),
      saveReferenceImages: vi.fn(),
      deleteReferenceImage: vi.fn(),
      getReferenceImageContent: vi.fn(),
      getImageContent: vi.fn(),
      resolveReferenceImagePaths: vi.fn(),
    };
    const framePromptProvider = {
      generateFramePrompt: vi.fn().mockResolvedValue({
        frameType: "start_frame",
        selectedCharacterIds: ["char_rin", "char_unknown", "char_ivo"],
        promptText: "清晨积水集市入口，林夏停在水线前，电影感构图。",
        negativePromptText: "模糊，低清晰度",
        rationale: "起始帧应突出林夏与入口堵路的关系。",
        rawResponse: '{"selectedCharacterIds":["char_rin","char_unknown","char_ivo"]}',
        provider: "gemini",
        model: "gemini-3.1-pro-preview",
      }),
    };

    const useCase = createProcessFramePromptGenerateTaskUseCase({
      taskRepository,
      projectRepository,
      taskFileStorage,
      shotImageRepository,
      shotImageStorage,
      shotScriptStorage,
      characterSheetRepository,
      characterSheetStorage,
      framePromptProvider,
      clock: {
        now: vi
          .fn()
          .mockReturnValueOnce("2026-03-24T00:14:00.000Z")
          .mockReturnValueOnce("2026-03-24T00:15:00.000Z"),
      },
    });

    await useCase.execute({ taskId: "task_frame_prompt_1" });

    expect(framePromptProvider.generateFramePrompt).toHaveBeenCalledWith(
      expect.objectContaining({
        frameType: "start_frame",
        currentShot: expect.objectContaining({
          id: "shot_1",
          shotCode: "S01-SG01-SH01",
          action: "她停住脚步。",
          frameDependency: "start_and_end_frame",
        }),
        segment: expect.objectContaining({
          sceneId: "scene_1",
          segmentId: "segment_1",
        }),
      }),
    );
    expect(shotImageRepository.updateFrame).toHaveBeenCalledWith(
      expect.objectContaining({
        id: "frame_segment_1_start",
        planStatus: "planned",
        selectedCharacterIds: ["char_rin", "char_ivo"],
        matchedReferenceImagePaths: [
          "projects/proj_20260324_ab12cd-my-story/character-sheets/char_rin/current.png",
        ],
        unmatchedCharacterIds: ["char_ivo"],
        promptTextSeed: "清晨积水集市入口，林夏停在水线前，电影感构图。",
        promptTextCurrent: "清晨积水集市入口，林夏停在水线前，电影感构图。",
        negativePromptTextCurrent: "模糊，低清晰度",
        promptUpdatedAt: "2026-03-24T00:15:00.000Z",
        sourceTaskId: "task_frame_prompt_1",
      }),
    );
    expect(shotImageStorage.writeFramePlanning).toHaveBeenCalledTimes(1);
    expect(shotImageStorage.writeFramePromptFiles).toHaveBeenCalledTimes(1);
    expect(taskFileStorage.writeTaskOutput).toHaveBeenCalledWith({
      task: expect.objectContaining({ id: "task_frame_prompt_1" }),
      output: {
        frameId: "frame_segment_1_start",
        selectedCharacterIds: ["char_rin", "char_ivo"],
        matchedReferenceImagePaths: [
          "projects/proj_20260324_ab12cd-my-story/character-sheets/char_rin/current.png",
        ],
        unmatchedCharacterIds: ["char_ivo"],
      },
    });
    expect(taskRepository.markSucceeded).toHaveBeenCalledWith({
      taskId: "task_frame_prompt_1",
      updatedAt: "2026-03-24T00:15:00.000Z",
      finishedAt: "2026-03-24T00:15:00.000Z",
    });
    expect(characterSheetStorage.readCurrentCharacterSheet).not.toHaveBeenCalled();
  });

  it("uses the matching scene segment when raw segment ids repeat", async () => {
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "task_frame_prompt_2",
        projectId: "proj_20260324_ab12cd",
        type: "frame_prompt_generate",
        status: "pending",
        queueName: "frame-prompt-generate",
        storageDir: "projects/proj_20260324_ab12cd-my-story/tasks/task_frame_prompt_2",
        inputRelPath: "tasks/task_frame_prompt_2/input.json",
        outputRelPath: "tasks/task_frame_prompt_2/output.json",
        logRelPath: "tasks/task_frame_prompt_2/log.txt",
        errorMessage: null,
        createdAt: "2026-03-24T00:12:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        startedAt: null,
        finishedAt: null,
      }),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_20260324_ab12cd",
        name: "My Story",
        slug: "my-story",
        storageDir: "projects/proj_20260324_ab12cd-my-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "master_plot_v1",
        currentCharacterSheetBatchId: "char_batch_v1",
        currentStoryboardId: "storyboard_v1",
        currentShotScriptId: "shot_script_v1",
        currentImageBatchId: "image_batch_task_20260324_images",
        status: "images_generating",
        createdAt: "2026-03-24T00:00:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        premiseUpdatedAt: "2026-03-24T00:00:00.000Z",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn().mockResolvedValue({
        taskId: "task_frame_prompt_2",
        projectId: "proj_20260324_ab12cd",
        taskType: "frame_prompt_generate",
        batchId: "image_batch_task_20260324_images",
        shotId: "shot_scene_2",
        frameId: "frame_scene_2__segment_1_start",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_2",
        frameType: "start_frame",
      }),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const shotImageRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listFramesByBatchId: vi.fn(),
      insertFrame: vi.fn(),
      findFrameById: vi.fn().mockResolvedValue({
        id: "frame_scene_2__segment_1_start",
        batchId: "image_batch_task_20260324_images",
        projectId: "proj_20260324_ab12cd",
        projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_2",
        order: 1,
        frameType: "start_frame",
        planStatus: "pending",
        imageStatus: "pending",
        selectedCharacterIds: [],
        matchedReferenceImagePaths: [],
        unmatchedCharacterIds: [],
        promptTextSeed: "",
        promptTextCurrent: "",
        negativePromptTextCurrent: null,
        promptUpdatedAt: null,
        imageAssetPath: null,
        imageWidth: null,
        imageHeight: null,
        provider: null,
        model: null,
        approvedAt: null,
        updatedAt: "2026-03-24T00:12:00.000Z",
        sourceTaskId: null,
        storageDir:
          "projects/proj_20260324_ab12cd-my-story/images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame",
        planningRelPath:
          "images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame/planning.json",
        promptSeedRelPath:
          "images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame/prompt.seed.txt",
        promptCurrentRelPath:
          "images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame/prompt.current.txt",
        currentImageRelPath:
          "images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame/current.png",
        currentMetadataRelPath:
          "images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame/current.json",
        promptVersionsStorageDir:
          "images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame/prompt.versions",
        versionsStorageDir:
          "images/batches/image_batch_task_20260324_images/segments/scene_2__segment_1/start-frame/versions",
      }),
      updateFrame: vi.fn(),
    };
    const shotImageStorage = {
      writeBatchManifest: vi.fn(),
      writeFramePlanning: vi.fn(),
      writeFramePromptFiles: vi.fn(),
      writeFramePromptVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      writeImageVersion: vi.fn(),
      readCurrentFrame: vi.fn(),
      resolveProjectAssetPath: vi.fn(),
    };
    const shotScriptStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeShotScriptVersion: vi.fn(),
      readShotScriptVersion: vi.fn(),
      writeCurrentShotScript: vi.fn(),
      readCurrentShotScript: vi.fn().mockResolvedValue({
        id: "shot_script_v1",
        title: "Episode 1 Shot Script",
        sourceStoryboardId: "storyboard_v1",
        sourceTaskId: "task_shot_script",
        updatedAt: "2026-03-24T00:10:00.000Z",
        approvedAt: "2026-03-24T00:10:00.000Z",
        segmentCount: 2,
        shotCount: 2,
        totalDurationSec: 11,
        segments: [
          {
            segmentId: "segment_1",
            sceneId: "scene_1",
            order: 1,
            name: "第一场",
            summary: "第一场摘要。",
            durationSec: 6,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [],
          },
          {
            segmentId: "segment_1",
            sceneId: "scene_2",
            order: 1,
            name: "第二场",
            summary: "第二场摘要。",
            durationSec: 5,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [
              {
                id: "shot_scene_2",
                sceneId: "scene_2",
                segmentId: "segment_1",
                order: 1,
                shotCode: "S02-SG01-SH01",
                durationSec: 5,
                purpose: "第二场。",
                visual: "第二场画面。",
                subject: "林夏",
                action: "回头。",
                frameDependency: "start_frame_only",
                dialogue: null,
                os: null,
                audio: "广播杂音。",
                transitionHint: null,
                continuityNotes: null,
              },
            ],
          },
        ],
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listCharactersByBatchId: vi.fn().mockResolvedValue([]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };
    const characterSheetStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writeBatchManifest: vi.fn(),
      writeGeneratedPrompt: vi.fn(),
      writeImageVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      readCurrentCharacterSheet: vi.fn(),
      listReferenceImages: vi.fn(),
      saveReferenceImages: vi.fn(),
      deleteReferenceImage: vi.fn(),
      getReferenceImageContent: vi.fn(),
      getImageContent: vi.fn(),
      resolveReferenceImagePaths: vi.fn(),
    };
    const framePromptProvider = {
      generateFramePrompt: vi.fn().mockResolvedValue({
        frameType: "start_frame",
        selectedCharacterIds: [],
        promptText: "第二场起始帧提示词。",
        negativePromptText: null,
        rationale: "聚焦第二场。",
        rawResponse: "{}",
        provider: "gemini",
        model: "gemini-3.1-pro-preview",
      }),
    };

    const useCase = createProcessFramePromptGenerateTaskUseCase({
      taskRepository,
      projectRepository,
      taskFileStorage,
      shotImageRepository,
      shotImageStorage,
      shotScriptStorage,
      characterSheetRepository,
      characterSheetStorage,
      framePromptProvider,
      clock: {
        now: vi
          .fn()
          .mockReturnValueOnce("2026-03-24T00:14:00.000Z")
          .mockReturnValueOnce("2026-03-24T00:15:00.000Z"),
      },
    });

    await useCase.execute({ taskId: "task_frame_prompt_2" });

    expect(framePromptProvider.generateFramePrompt).toHaveBeenCalledWith(
      expect.objectContaining({
        segment: expect.objectContaining({
          sceneId: "scene_2",
          summary: "第二场摘要。",
          shots: [expect.objectContaining({ shotCode: "S02-SG01-SH01" })],
        }),
      }),
    );
  });

  it("passes start-frame continuity context when generating an end-frame prompt", async () => {
    const shot = createShotReferenceRecord({
      id: "shot_ref_prompt_end_context",
      batchId: "image_batch_prompt_end_context",
      projectId: "proj_prompt_end_context",
      projectStorageDir: "projects/proj_prompt_end_context-story",
      sourceShotScriptId: "shot_script_prompt_end_context",
      sceneId: "scene_1",
      segmentId: "segment_1",
      shotId: "shot_1",
      shotCode: "S01-SG01-SH01",
      segmentOrder: 1,
      shotOrder: 1,
      durationSec: 4,
      frameDependency: "start_and_end_frame",
      updatedAt: "2026-03-24T00:12:00.000Z",
      startFrame: {
        id: "frame_start_prompt_context",
        planStatus: "planned",
        imageStatus: "approved",
        selectedCharacterIds: ["char_rin", "char_ivo"],
        promptTextCurrent: "首帧 Prompt，林夏站在雨夜市场入口。",
        imageAssetPath:
          "images/batches/image_batch_prompt_end_context/shots/scene_1/segment_1/shot_1/start-frame/current.png",
      },
      endFrame: {
        id: "frame_end_prompt_context",
        planStatus: "pending",
        imageStatus: "pending",
      },
    });
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "task_frame_prompt_end_context",
        projectId: "proj_prompt_end_context",
        type: "frame_prompt_generate",
        status: "pending",
        queueName: "frame-prompt-generate",
        storageDir: "projects/proj_prompt_end_context-story/tasks/task_frame_prompt_end_context",
        inputRelPath: "tasks/task_frame_prompt_end_context/input.json",
        outputRelPath: "tasks/task_frame_prompt_end_context/output.json",
        logRelPath: "tasks/task_frame_prompt_end_context/log.txt",
        errorMessage: null,
        createdAt: "2026-03-24T00:12:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        startedAt: null,
        finishedAt: null,
      }),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_prompt_end_context",
        name: "Prompt Context Story",
        slug: "prompt-context-story",
        storageDir: "projects/proj_prompt_end_context-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "master_plot_prompt_end_context",
        currentCharacterSheetBatchId: null,
        currentStoryboardId: "storyboard_prompt_end_context",
        currentShotScriptId: "shot_script_prompt_end_context",
        currentImageBatchId: "image_batch_prompt_end_context",
        status: "images_generating",
        createdAt: "2026-03-24T00:00:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        premiseUpdatedAt: "2026-03-24T00:00:00.000Z",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn().mockResolvedValue({
        taskId: "task_frame_prompt_end_context",
        projectId: "proj_prompt_end_context",
        taskType: "frame_prompt_generate",
        batchId: "image_batch_prompt_end_context",
        shotId: "shot_1",
        frameId: "frame_end_prompt_context",
        sourceShotScriptId: "shot_script_prompt_end_context",
        segmentId: "segment_1",
        sceneId: "scene_1",
        frameType: "end_frame",
      }),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const shotImageRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listFramesByBatchId: vi.fn(),
      listShotsByBatchId: vi.fn().mockResolvedValue([shot]),
      insertFrame: vi.fn(),
      insertShot: vi.fn(),
      findFrameById: vi.fn().mockResolvedValue(null),
      findShotById: vi.fn(),
      updateFrame: vi.fn(),
      updateShot: vi.fn(),
    };
    const shotImageStorage = {
      writeBatchManifest: vi.fn(),
      writeFramePlanning: vi.fn(),
      writeFramePromptFiles: vi.fn(),
      writeFramePromptVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      writeImageVersion: vi.fn(),
      readCurrentFrame: vi.fn(),
      resolveProjectAssetPath: vi.fn(),
    };
    const shotScriptStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeShotScriptVersion: vi.fn(),
      readShotScriptVersion: vi.fn(),
      writeCurrentShotScript: vi.fn(),
      readCurrentShotScript: vi.fn().mockResolvedValue({
        id: "shot_script_prompt_end_context",
        title: "Episode 1 Shot Script",
        sourceStoryboardId: "storyboard_prompt_end_context",
        sourceTaskId: "task_shot_script_prompt_end_context",
        updatedAt: "2026-03-24T00:10:00.000Z",
        approvedAt: "2026-03-24T00:10:00.000Z",
        segmentCount: 1,
        shotCount: 1,
        totalDurationSec: 4,
        segments: [
          {
            segmentId: "segment_1",
            sceneId: "scene_1",
            order: 1,
            name: "雨夜市场",
            summary: "林夏在市场入口确认对手堵住出口。",
            durationSec: 4,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [
              {
                id: "shot_1",
                sceneId: "scene_1",
                segmentId: "segment_1",
                order: 1,
                shotCode: "S01-SG01-SH01",
                durationSec: 4,
                purpose: "展现尾帧收束。",
                visual: "雨夜市场入口，霓虹在积水里拉成长条。",
                subject: "林夏、伊沃",
                action: "林夏停在出口前，伊沃在后景看向她。",
                frameDependency: "start_and_end_frame",
                dialogue: null,
                os: "结束了。",
                audio: "雨声渐弱。",
                transitionHint: "切到下一镜近景。",
                continuityNotes: "林夏左肩背包不能丢。",
              },
            ],
          },
        ],
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listCharactersByBatchId: vi.fn().mockResolvedValue([]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };
    const characterSheetStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writeBatchManifest: vi.fn(),
      writeGeneratedPrompt: vi.fn(),
      writeImageVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      readCurrentCharacterSheet: vi.fn(),
      listReferenceImages: vi.fn(),
      saveReferenceImages: vi.fn(),
      deleteReferenceImage: vi.fn(),
      getReferenceImageContent: vi.fn(),
      getImageContent: vi.fn(),
      resolveReferenceImagePaths: vi.fn(),
    };
    const framePromptProvider = {
      generateFramePrompt: vi.fn().mockResolvedValue({
        frameType: "end_frame",
        selectedCharacterIds: [],
        promptText: "尾帧 Prompt。",
        negativePromptText: null,
        rationale: "基于首帧连续性推进。",
        rawResponse: "{}",
        provider: "gemini",
        model: "gemini-3.1-pro-preview",
      }),
    };

    const useCase = createProcessFramePromptGenerateTaskUseCase({
      taskRepository,
      projectRepository,
      taskFileStorage,
      shotImageRepository,
      shotImageStorage,
      shotScriptStorage,
      characterSheetRepository,
      characterSheetStorage,
      framePromptProvider,
      clock: {
        now: vi
          .fn()
          .mockReturnValueOnce("2026-03-24T00:14:00.000Z")
          .mockReturnValueOnce("2026-03-24T00:15:00.000Z"),
      },
    });

    await useCase.execute({ taskId: "task_frame_prompt_end_context" });

    expect(framePromptProvider.generateFramePrompt).toHaveBeenCalledWith(
      expect.objectContaining({
        frameType: "end_frame",
        startFrameContext: {
          promptTextCurrent: "首帧 Prompt，林夏站在雨夜市场入口。",
          selectedCharacterIds: ["char_rin", "char_ivo"],
          imageStatus: "approved",
          imageAssetPath:
            "images/batches/image_batch_prompt_end_context/shots/scene_1/segment_1/shot_1/start-frame/current.png",
        },
      }),
    );
  });

  it("passes approved scene context into frame prompt generation and falls back to scene-aware text", async () => {
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "task_frame_prompt_scene_context",
        projectId: "proj_20260324_ab12cd",
        type: "frame_prompt_generate",
        status: "pending",
        queueName: "frame-prompt-generate",
        storageDir: "projects/proj_20260324_ab12cd-my-story/tasks/task_frame_prompt_scene_context",
        inputRelPath: "tasks/task_frame_prompt_scene_context/input.json",
        outputRelPath: "tasks/task_frame_prompt_scene_context/output.json",
        logRelPath: "tasks/task_frame_prompt_scene_context/log.txt",
        errorMessage: null,
        createdAt: "2026-03-24T00:12:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        startedAt: null,
        finishedAt: null,
      }),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_20260324_ab12cd",
        name: "My Story",
        slug: "my-story",
        storageDir: "projects/proj_20260324_ab12cd-my-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "master_plot_v1",
        currentCharacterSheetBatchId: "char_batch_v1",
        currentSceneSheetBatchId: "scene_batch_v1",
        currentStoryboardId: "storyboard_v1",
        currentShotScriptId: "shot_script_v1",
        currentImageBatchId: "image_batch_task_20260324_images",
        status: "images_generating",
        createdAt: "2026-03-24T00:00:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        premiseUpdatedAt: "2026-03-24T00:00:00.000Z",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn().mockResolvedValue({
        taskId: "task_frame_prompt_scene_context",
        projectId: "proj_20260324_ab12cd",
        taskType: "frame_prompt_generate",
        batchId: "image_batch_task_20260324_images",
        shotId: "shot_1",
        frameId: "frame_segment_1_start",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_1",
        frameType: "start_frame",
      }),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const shotImageRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listFramesByBatchId: vi.fn(),
      insertFrame: vi.fn(),
      findFrameById: vi.fn().mockResolvedValue({
        id: "frame_segment_1_start",
        batchId: "image_batch_task_20260324_images",
        projectId: "proj_20260324_ab12cd",
        projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_1",
        order: 1,
        frameType: "start_frame",
        planStatus: "pending",
        imageStatus: "pending",
        selectedCharacterIds: [],
        matchedReferenceImagePaths: [],
        unmatchedCharacterIds: [],
        promptTextSeed: "",
        promptTextCurrent: "",
        negativePromptTextCurrent: null,
        promptUpdatedAt: null,
        imageAssetPath: null,
        imageWidth: null,
        imageHeight: null,
        provider: null,
        model: null,
        approvedAt: null,
        updatedAt: "2026-03-24T00:12:00.000Z",
        sourceTaskId: null,
        storageDir: "ignored",
        planningRelPath: "ignored",
        promptSeedRelPath: "ignored",
        promptCurrentRelPath: "ignored",
        currentImageRelPath: "ignored",
        currentMetadataRelPath: "ignored",
        promptVersionsStorageDir: "ignored",
        versionsStorageDir: "ignored",
      }),
      updateFrame: vi.fn(),
    };
    const shotImageStorage = {
      writeBatchManifest: vi.fn(),
      writeFramePlanning: vi.fn(),
      writeFramePromptFiles: vi.fn(),
      writeFramePromptVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      writeImageVersion: vi.fn(),
      readCurrentFrame: vi.fn(),
      resolveProjectAssetPath: vi.fn(),
    };
    const shotScriptStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeShotScriptVersion: vi.fn(),
      readShotScriptVersion: vi.fn(),
      writeCurrentShotScript: vi.fn(),
      readCurrentShotScript: vi.fn().mockResolvedValue({
        id: "shot_script_v1",
        title: "Episode 1 Shot Script",
        sourceStoryboardId: "storyboard_v1",
        sourceTaskId: "task_shot_script",
        updatedAt: "2026-03-24T00:10:00.000Z",
        approvedAt: "2026-03-24T00:10:00.000Z",
        segmentCount: 1,
        shotCount: 1,
        totalDurationSec: 6,
        segments: [
          {
            segmentId: "segment_1",
            sceneId: "scene_1",
            order: 1,
            name: "集市压境",
            summary: "林夏确认对手已经堵住出口。",
            durationSec: 6,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [
              {
                id: "shot_1",
                sceneId: "scene_1",
                segmentId: "segment_1",
                order: 1,
                shotCode: "S01-SG01-SH01",
                durationSec: 3,
                purpose: "交代堵路。",
                visual: "清晨积水集市入口，棚顶压低，积水映着冷暖霓虹。",
                subject: "林夏",
                action: "她停住脚步，看向已经被堵住的出口。",
                frameDependency: "start_and_end_frame",
                dialogue: null,
                os: null,
                audio: "雨声与水声。",
                transitionHint: null,
                continuityNotes: "入口招牌和湿滑地面保持连续。",
              },
            ],
          },
        ],
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listCharactersByBatchId: vi.fn().mockResolvedValue([]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };
    const characterSheetStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writeBatchManifest: vi.fn(),
      writeGeneratedPrompt: vi.fn(),
      writeImageVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      readCurrentCharacterSheet: vi.fn(),
      listReferenceImages: vi.fn(),
      saveReferenceImages: vi.fn(),
      deleteReferenceImage: vi.fn(),
      getReferenceImageContent: vi.fn(),
      getImageContent: vi.fn(),
      resolveReferenceImagePaths: vi.fn(),
    };
    const sceneSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listScenesByBatchId: vi.fn().mockResolvedValue([
        {
          id: "scene_sheet_market",
          projectId: "proj_20260324_ab12cd",
          projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
          batchId: "scene_batch_v1",
          sourceMasterPlotId: "master_plot_v1",
          sourceCharacterSheetBatchId: "char_batch_v1",
          sceneName: "雨夜市场入口",
          scenePurpose: "作为追逐戏前的核心环境锚点。",
          promptTextGenerated: "雨夜市场入口。",
          promptTextCurrent: "雨夜市场入口，狭窄棚顶、潮湿地面、冷暖混合霓虹，出口通道逼仄。",
          constraintsText: "保持棚顶结构、入口招牌、积水反光和逼仄出口关系。",
          imageAssetPath: "scene-sheets/batches/scene_batch_v1/scenes/scene_sheet_market/current.png",
          imageWidth: 1280,
          imageHeight: 720,
          provider: "vector-engine",
          model: "scene-v1",
          status: "approved",
          updatedAt: "2026-03-24T00:08:00.000Z",
          approvedAt: "2026-03-24T00:09:00.000Z",
          sourceTaskId: "task_scene_market",
          storageDir: "ignored",
          currentImageRelPath: "ignored",
          currentMetadataRelPath: "ignored",
          promptGeneratedRelPath: "ignored",
          promptCurrentRelPath: "ignored",
          promptVariablesRelPath: "ignored",
          imagePromptRelPath: "ignored",
          versionsStorageDir: "ignored",
        },
      ]),
      insertScene: vi.fn(),
      findSceneById: vi.fn(),
      updateScene: vi.fn(),
    };
    const framePromptProvider = {
      generateFramePrompt: vi.fn().mockResolvedValue({
        frameType: "start_frame",
        selectedCharacterIds: [],
        selectedSceneId: "scene_sheet_market",
        promptText: "清晨积水集市入口，林夏停在被堵住的出口前。",
        negativePromptText: null,
        rationale: "同时保留人物和场景关系。",
        rawResponse: "{}",
        provider: "gemini",
        model: "gemini-3.1-pro-preview",
      }),
    };

    const useCase = createProcessFramePromptGenerateTaskUseCase({
      taskRepository,
      projectRepository,
      taskFileStorage,
      shotImageRepository,
      shotImageStorage,
      shotScriptStorage,
      characterSheetRepository,
      characterSheetStorage,
      sceneSheetRepository: sceneSheetRepository as any,
      framePromptProvider,
      clock: {
        now: vi
          .fn()
          .mockReturnValueOnce("2026-03-24T00:14:00.000Z")
          .mockReturnValueOnce("2026-03-24T00:15:00.000Z"),
      },
    } as any);

    await useCase.execute({ taskId: "task_frame_prompt_scene_context" });

    expect(framePromptProvider.generateFramePrompt).toHaveBeenCalledWith(
      expect.objectContaining({
        sceneCandidates: expect.arrayContaining([
          expect.objectContaining({
            sceneId: "scene_sheet_market",
            sceneName: "雨夜市场入口",
            promptTextCurrent: "雨夜市场入口，狭窄棚顶、潮湿地面、冷暖混合霓虹，出口通道逼仄。",
          }),
        ]),
        sceneContext: expect.objectContaining({
          source: "shot_script",
          sceneId: "scene_1",
          environmentSummary: expect.stringContaining("林夏确认对手已经堵住出口"),
        }),
      }),
    );
  });

  it("passes scene candidates to the model and trusts selectedSceneId from the response", async () => {
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "task_frame_prompt_scene_context_confidence",
        projectId: "proj_20260324_ab12cd",
        type: "frame_prompt_generate",
        status: "pending",
        queueName: "frame-prompt-generate",
        storageDir: "projects/proj_20260324_ab12cd-my-story/tasks/task_frame_prompt_scene_context_confidence",
        inputRelPath: "tasks/task_frame_prompt_scene_context_confidence/input.json",
        outputRelPath: "tasks/task_frame_prompt_scene_context_confidence/output.json",
        logRelPath: "tasks/task_frame_prompt_scene_context_confidence/log.txt",
        errorMessage: null,
        createdAt: "2026-03-24T00:12:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        startedAt: null,
        finishedAt: null,
      }),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_20260324_ab12cd",
        name: "My Story",
        slug: "my-story",
        storageDir: "projects/proj_20260324_ab12cd-my-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "master_plot_v1",
        currentCharacterSheetBatchId: "char_batch_v1",
        currentSceneSheetBatchId: "scene_batch_v1",
        currentStoryboardId: "storyboard_v1",
        currentShotScriptId: "shot_script_v1",
        currentImageBatchId: "image_batch_task_20260324_images",
        status: "images_generating",
        createdAt: "2026-03-24T00:00:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        premiseUpdatedAt: "2026-03-24T00:00:00.000Z",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn().mockResolvedValue({
        taskId: "task_frame_prompt_scene_context_confidence",
        projectId: "proj_20260324_ab12cd",
        taskType: "frame_prompt_generate",
        batchId: "image_batch_task_20260324_images",
        shotId: "shot_3_3_2",
        frameId: "frame_scene_3_segment_3_start",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_3",
        sceneId: "scene_3",
        frameType: "start_frame",
      }),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const shotImageRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listFramesByBatchId: vi.fn(),
      insertFrame: vi.fn(),
      findFrameById: vi.fn().mockResolvedValue({
        id: "frame_scene_3_segment_3_start",
        batchId: "image_batch_task_20260324_images",
        projectId: "proj_20260324_ab12cd",
        projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_3",
        sceneId: "scene_3",
        order: 1,
        frameType: "start_frame",
        planStatus: "pending",
        imageStatus: "pending",
        selectedCharacterIds: [],
        matchedReferenceImagePaths: [],
        unmatchedCharacterIds: [],
        promptTextSeed: "",
        promptTextCurrent: "",
        negativePromptTextCurrent: null,
        promptUpdatedAt: null,
        imageAssetPath: null,
        imageWidth: null,
        imageHeight: null,
        provider: null,
        model: null,
        approvedAt: null,
        updatedAt: "2026-03-24T00:12:00.000Z",
        sourceTaskId: null,
        storageDir: "ignored",
        planningRelPath: "ignored",
        promptSeedRelPath: "ignored",
        promptCurrentRelPath: "ignored",
        currentImageRelPath: "ignored",
        currentMetadataRelPath: "ignored",
        promptVersionsStorageDir: "ignored",
        versionsStorageDir: "ignored",
      }),
      updateFrame: vi.fn(),
    };
    const shotImageStorage = {
      writeBatchManifest: vi.fn(),
      writeFramePlanning: vi.fn(),
      writeFramePromptFiles: vi.fn(),
      writeFramePromptVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      writeImageVersion: vi.fn(),
      readCurrentFrame: vi.fn(),
      resolveProjectAssetPath: vi.fn(),
    };
    const shotScriptStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeShotScriptVersion: vi.fn(),
      readShotScriptVersion: vi.fn(),
      writeCurrentShotScript: vi.fn(),
      readCurrentShotScript: vi.fn().mockResolvedValue({
        id: "shot_script_v1",
        title: "Episode 1 Shot Script",
        sourceStoryboardId: "storyboard_v1",
        sourceTaskId: "task_shot_script",
        updatedAt: "2026-03-24T00:10:00.000Z",
        approvedAt: "2026-03-24T00:10:00.000Z",
        segmentCount: 1,
        shotCount: 1,
        totalDurationSec: 4,
        segments: [
          {
            segmentId: "segment_3",
            sceneId: "scene_3",
            order: 3,
            name: "巨额投资达成",
            summary:
              "财团总裁认出林峰身份并给出镶金名片，林峰看清背后的投资金额后激动鞠躬，运势在这一刻彻底逆转。",
            durationSec: 4,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [
              {
                id: "shot_3_3_2",
                sceneId: "scene_3",
                segmentId: "segment_3",
                order: 2,
                shotCode: "S03_03_02",
                durationSec: 4,
                purpose: "突出财团总裁给出投资意向的果断与手笔。",
                visual: "特写。财团总裁手中拿着一张镶金名片，正用钢笔在名片背面快速写下一串数字。",
                subject: "财团总裁",
                action: "手持钢笔在镶金名片背面书写数字。",
                frameDependency: "start_frame_only",
                dialogue: "我看过你的企划，",
                os: null,
                audio: "笔尖划过纸面的快速写字声。",
                transitionHint: "动作连续切回中景。",
                continuityNotes: "名片需带有镶金边，钢笔样式需保持高档感。",
              },
            ],
          },
        ],
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listCharactersByBatchId: vi.fn().mockResolvedValue([]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };
    const characterSheetStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writeBatchManifest: vi.fn(),
      writeGeneratedPrompt: vi.fn(),
      writeImageVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      readCurrentCharacterSheet: vi.fn(),
      listReferenceImages: vi.fn(),
      saveReferenceImages: vi.fn(),
      deleteReferenceImage: vi.fn(),
      getReferenceImageContent: vi.fn(),
      getImageContent: vi.fn(),
      resolveReferenceImagePaths: vi.fn(),
    };
    const sceneSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listScenesByBatchId: vi.fn().mockResolvedValue([
        {
          id: "scene_sheet_ritual",
          projectId: "proj_20260324_ab12cd",
          projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
          batchId: "scene_batch_v1",
          sourceMasterPlotId: "master_plot_v1",
          sourceCharacterSheetBatchId: "char_batch_v1",
          sceneName: "化太岁仪式空间",
          scenePurpose: "承接转运仪式与命运逆转的核心内景空间。",
          promptTextGenerated: "玄学仪式室。",
          promptTextCurrent:
            "玄学仪式室，暖金烛光映照木质法坛与香炉，符纸、供器、护身符整齐陈设，空间安静封闭，带有可感知的净化与转运氛围。",
          constraintsText: "保持法坛、香炉、符纸和暖金烛光关系稳定。",
          imageAssetPath: "scene-sheets/batches/scene_batch_v1/scenes/scene_sheet_ritual/current.png",
          imageWidth: 1280,
          imageHeight: 720,
          provider: "vector-engine",
          model: "scene-v1",
          status: "approved",
          updatedAt: "2026-03-24T00:08:00.000Z",
          approvedAt: "2026-03-24T00:09:00.000Z",
          sourceTaskId: "task_scene_ritual",
          storageDir: "ignored",
          currentImageRelPath: "ignored",
          currentMetadataRelPath: "ignored",
          promptGeneratedRelPath: "ignored",
          promptCurrentRelPath: "ignored",
          promptVariablesRelPath: "ignored",
          imagePromptRelPath: "ignored",
          versionsStorageDir: "ignored",
        },
        {
          id: "scene_sheet_lobby",
          projectId: "proj_20260324_ab12cd",
          projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
          batchId: "scene_batch_v1",
          sourceMasterPlotId: "master_plot_v1",
          sourceCharacterSheetBatchId: "char_batch_v1",
          sceneName: "财团大厅",
          scenePurpose: "承接命运翻盘、获得投资的核心公共商务场景。",
          promptTextGenerated: "高挑财团大厅。",
          promptTextCurrent:
            "高挑财团大厅，石材地面与玻璃立面形成通透纵深，冷白天光从高处洒下，入口开阔，空间兼具商务秩序与戏剧性危机感。",
          constraintsText: "保持高挑大厅结构、石材地面、玻璃立面和开阔入口关系。",
          imageAssetPath: "scene-sheets/batches/scene_batch_v1/scenes/scene_sheet_lobby/current.png",
          imageWidth: 1280,
          imageHeight: 720,
          provider: "vector-engine",
          model: "scene-v1",
          status: "approved",
          updatedAt: "2026-03-24T00:08:00.000Z",
          approvedAt: "2026-03-24T00:09:00.000Z",
          sourceTaskId: "task_scene_lobby",
          storageDir: "ignored",
          currentImageRelPath: "ignored",
          currentMetadataRelPath: "ignored",
          promptGeneratedRelPath: "ignored",
          promptCurrentRelPath: "ignored",
          promptVariablesRelPath: "ignored",
          imagePromptRelPath: "ignored",
          versionsStorageDir: "ignored",
        },
      ]),
      insertScene: vi.fn(),
      findSceneById: vi.fn(),
      updateScene: vi.fn(),
    };
    const framePromptProvider = {
      generateFramePrompt: vi.fn().mockResolvedValue({
        frameType: "start_frame",
        selectedCharacterIds: [],
        selectedSceneId: "scene_sheet_lobby",
        promptText: "财团总裁在大厅内写下投资数字。",
        negativePromptText: null,
        rationale: "优先保留正确的大厅环境锚点。",
        rawResponse: "{}",
        provider: "gemini",
        model: "gemini-3.1-pro-preview",
      }),
    };

    const useCase = createProcessFramePromptGenerateTaskUseCase({
      taskRepository,
      projectRepository,
      taskFileStorage,
      shotImageRepository,
      shotImageStorage,
      shotScriptStorage,
      characterSheetRepository,
      characterSheetStorage,
      sceneSheetRepository: sceneSheetRepository as any,
      framePromptProvider,
      clock: {
        now: vi
          .fn()
          .mockReturnValueOnce("2026-03-24T00:14:00.000Z")
          .mockReturnValueOnce("2026-03-24T00:15:00.000Z"),
      },
    } as any);

    await useCase.execute({ taskId: "task_frame_prompt_scene_context_confidence" });

    expect(framePromptProvider.generateFramePrompt).toHaveBeenCalledTimes(1);
    const framePromptInput = vi.mocked(framePromptProvider.generateFramePrompt).mock.calls[0]?.[0];
    expect(framePromptInput).toBeDefined();
    expect(framePromptInput?.sceneCandidates).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          sceneId: "scene_sheet_ritual",
          sceneName: "化太岁仪式空间",
        }),
        expect.objectContaining({
          sceneId: "scene_sheet_lobby",
          sceneName: "财团大厅",
        }),
      ]),
    );
    expect(framePromptInput?.sceneContext).toEqual(
      expect.objectContaining({
        source: "shot_script",
        sceneId: "scene_3",
        sceneName: "巨额投资达成",
        environmentSummary: expect.stringContaining("镶金名片"),
      }),
    );

    expect(shotImageStorage.writeFramePlanning).toHaveBeenCalledWith(
      expect.objectContaining({
        planning: expect.objectContaining({
          selectedSceneId: "scene_sheet_lobby",
          selectedSceneName: "财团大厅",
        }),
      }),
    );
  });

  it("marks the frame plan as failed when prompt generation fails so regeneration stays available", async () => {
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "task_frame_prompt_3",
        projectId: "proj_20260324_ab12cd",
        type: "frame_prompt_generate",
        status: "pending",
        queueName: "frame-prompt-generate",
        storageDir: "projects/proj_20260324_ab12cd-my-story/tasks/task_frame_prompt_3",
        inputRelPath: "tasks/task_frame_prompt_3/input.json",
        outputRelPath: "tasks/task_frame_prompt_3/output.json",
        logRelPath: "tasks/task_frame_prompt_3/log.txt",
        errorMessage: null,
        createdAt: "2026-03-24T00:12:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        startedAt: null,
        finishedAt: null,
      }),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_20260324_ab12cd",
        name: "My Story",
        slug: "my-story",
        storageDir: "projects/proj_20260324_ab12cd-my-story",
        premiseRelPath: "premise/v1.md",
        premiseBytes: 88,
        currentMasterPlotId: "master_plot_v1",
        currentCharacterSheetBatchId: "char_batch_v1",
        currentStoryboardId: "storyboard_v1",
        currentShotScriptId: "shot_script_v1",
        currentImageBatchId: "image_batch_task_20260324_images",
        status: "images_generating",
        createdAt: "2026-03-24T00:00:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        premiseUpdatedAt: "2026-03-24T00:00:00.000Z",
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn().mockResolvedValue({
        taskId: "task_frame_prompt_3",
        projectId: "proj_20260324_ab12cd",
        taskType: "frame_prompt_generate",
        batchId: "image_batch_task_20260324_images",
        shotId: "shot_1",
        frameId: "frame_segment_1_end",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_1",
        frameType: "end_frame",
      }),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const shotImageRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listFramesByBatchId: vi.fn(),
      insertFrame: vi.fn(),
      findFrameById: vi.fn().mockResolvedValue({
        id: "frame_segment_1_end",
        batchId: "image_batch_task_20260324_images",
        projectId: "proj_20260324_ab12cd",
        projectStorageDir: "projects/proj_20260324_ab12cd-my-story",
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_1",
        order: 1,
        frameType: "end_frame",
        planStatus: "pending",
        imageStatus: "pending",
        selectedCharacterIds: [],
        matchedReferenceImagePaths: [],
        unmatchedCharacterIds: [],
        promptTextSeed: "",
        promptTextCurrent: "",
        negativePromptTextCurrent: null,
        promptUpdatedAt: null,
        imageAssetPath: null,
        imageWidth: null,
        imageHeight: null,
        provider: null,
        model: null,
        approvedAt: null,
        updatedAt: "2026-03-24T00:12:00.000Z",
        sourceTaskId: null,
        storageDir:
          "projects/proj_20260324_ab12cd-my-story/images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame",
        planningRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame/planning.json",
        promptSeedRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame/prompt.seed.txt",
        promptCurrentRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame/prompt.current.txt",
        currentImageRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame/current.png",
        currentMetadataRelPath:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame/current.json",
        promptVersionsStorageDir:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame/prompt.versions",
        versionsStorageDir:
          "images/batches/image_batch_task_20260324_images/segments/segment_1/end-frame/versions",
      }),
      updateFrame: vi.fn(),
    };
    const shotImageStorage = {
      writeBatchManifest: vi.fn(),
      writeFramePlanning: vi.fn(),
      writeFramePromptFiles: vi.fn(),
      writeFramePromptVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      writeImageVersion: vi.fn(),
      readCurrentFrame: vi.fn(),
      resolveProjectAssetPath: vi.fn(),
    };
    const shotScriptStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeShotScriptVersion: vi.fn(),
      readShotScriptVersion: vi.fn(),
      writeCurrentShotScript: vi.fn(),
      readCurrentShotScript: vi.fn().mockResolvedValue({
        id: "shot_script_v1",
        title: "Episode 1 Shot Script",
        sourceStoryboardId: "storyboard_v1",
        sourceTaskId: "task_shot_script",
        updatedAt: "2026-03-24T00:10:00.000Z",
        approvedAt: "2026-03-24T00:10:00.000Z",
        segmentCount: 1,
        shotCount: 1,
        totalDurationSec: 6,
        segments: [
          {
            segmentId: "segment_1",
            sceneId: "scene_1",
            order: 1,
            name: "集市压境",
            summary: "林夏确认对手已经堵住出口。",
            durationSec: 6,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [
              {
                id: "shot_1",
                sceneId: "scene_1",
                segmentId: "segment_1",
                order: 1,
                shotCode: "S01-SG01-SH01",
                durationSec: 3,
                purpose: "交代堵路。",
                visual: "清晨积水集市入口。",
                subject: "林夏",
                action: "她停住脚步。",
                frameDependency: "start_and_end_frame",
                dialogue: null,
                os: null,
                audio: "雨声与水声。",
                transitionHint: null,
                continuityNotes: null,
              },
            ],
          },
        ],
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listCharactersByBatchId: vi.fn().mockResolvedValue([]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };
    const characterSheetStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writeBatchManifest: vi.fn(),
      writeGeneratedPrompt: vi.fn(),
      writeImageVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      readCurrentCharacterSheet: vi.fn(),
      listReferenceImages: vi.fn(),
      saveReferenceImages: vi.fn(),
      deleteReferenceImage: vi.fn(),
      getReferenceImageContent: vi.fn(),
      getImageContent: vi.fn(),
      resolveReferenceImagePaths: vi.fn(),
    };
    const framePromptProvider = {
      generateFramePrompt: vi.fn().mockRejectedValue(new Error("VectorEngine Gemini 503")),
    };

    const useCase = createProcessFramePromptGenerateTaskUseCase({
      taskRepository,
      projectRepository,
      taskFileStorage,
      shotImageRepository,
      shotImageStorage,
      shotScriptStorage,
      characterSheetRepository,
      characterSheetStorage,
      framePromptProvider,
      clock: {
        now: vi
          .fn()
          .mockReturnValueOnce("2026-03-24T00:14:00.000Z")
          .mockReturnValueOnce("2026-03-24T00:15:00.000Z"),
      },
    });

    await expect(useCase.execute({ taskId: "task_frame_prompt_3" })).rejects.toThrow(
      "VectorEngine Gemini 503",
    );

    expect(shotImageRepository.updateFrame).toHaveBeenCalledWith(
      expect.objectContaining({
        id: "frame_segment_1_end",
        planStatus: "plan_failed",
        updatedAt: "2026-03-24T00:15:00.000Z",
      }),
    );
    expect(taskRepository.markFailed).toHaveBeenCalledWith({
      taskId: "task_frame_prompt_3",
      errorMessage: "VectorEngine Gemini 503",
      updatedAt: "2026-03-24T00:15:00.000Z",
      finishedAt: "2026-03-24T00:15:00.000Z",
    });
  });

  it("updates the owning shot slot when the repository exposes shot-scoped records", async () => {
    const shot = createShotReferenceRecord({
      id: "shot_ref_image_batch_1_scene_1_segment_1_shot_1",
      batchId: "image_batch_1",
      projectId: "proj_1",
      projectStorageDir: "projects/proj_1-my-story",
      sourceShotScriptId: "shot_script_v1",
      sceneId: "scene_1",
      segmentId: "segment_1",
      shotId: "shot_1",
      shotCode: "S01-SG01-SH01",
      segmentOrder: 1,
      shotOrder: 1,
      durationSec: 3,
      frameDependency: "start_and_end_frame",
      updatedAt: "2026-03-24T00:12:00.000Z",
    });
    const taskRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "task_frame_prompt_4",
        projectId: "proj_1",
        type: "frame_prompt_generate",
        status: "pending",
        queueName: "frame-prompt-generate",
        storageDir: "projects/proj_1-my-story/tasks/task_frame_prompt_4",
        inputRelPath: "tasks/task_frame_prompt_4/input.json",
        outputRelPath: "tasks/task_frame_prompt_4/output.json",
        logRelPath: "tasks/task_frame_prompt_4/log.txt",
        errorMessage: null,
        createdAt: "2026-03-24T00:12:00.000Z",
        updatedAt: "2026-03-24T00:12:00.000Z",
        startedAt: null,
        finishedAt: null,
      }),
      findLatestByProjectId: vi.fn(),
      delete: vi.fn(),
      markRunning: vi.fn(),
      markSucceeded: vi.fn(),
      markFailed: vi.fn(),
    };
    const projectRepository = {
      insert: vi.fn(),
      findById: vi.fn().mockResolvedValue({
        id: "proj_1",
        storageDir: "projects/proj_1-my-story",
        currentCharacterSheetBatchId: null,
      }),
      updatePremiseMetadata: vi.fn(),
      updateCurrentMasterPlot: vi.fn(),
      updateCurrentCharacterSheetBatch: vi.fn(),
      updateCurrentStoryboard: vi.fn(),
      updateCurrentShotScript: vi.fn(),
      updateCurrentImageBatch: vi.fn(),
      updateStatus: vi.fn(),
      listAll: vi.fn(),
    };
    const taskFileStorage = {
      createTaskArtifacts: vi.fn(),
      readTaskInput: vi.fn().mockResolvedValue({
        taskId: "task_frame_prompt_4",
        projectId: "proj_1",
        taskType: "frame_prompt_generate",
        batchId: "image_batch_1",
        shotId: "shot_1",
        frameId: shot.startFrame.id,
        sourceShotScriptId: "shot_script_v1",
        segmentId: "segment_1",
        sceneId: "scene_1",
        frameType: "start_frame",
      }),
      writeTaskOutput: vi.fn(),
      appendTaskLog: vi.fn(),
    };
    const shotImageRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      findCurrentBatchByProjectId: vi.fn(),
      listFramesByBatchId: vi.fn(),
      listShotsByBatchId: vi.fn(),
      insertFrame: vi.fn(),
      insertShot: vi.fn(),
      findFrameById: vi.fn().mockResolvedValue(null),
      findShotById: vi.fn().mockResolvedValue(shot),
      updateFrame: vi.fn(),
      updateShot: vi.fn(),
    };
    const shotImageStorage = {
      writeBatchManifest: vi.fn(),
      writeFramePlanning: vi.fn(),
      writeFramePromptFiles: vi.fn(),
      writeFramePromptVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      writeImageVersion: vi.fn(),
      readCurrentFrame: vi.fn(),
      resolveProjectAssetPath: vi.fn(),
    };
    const shotScriptStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writePromptSnapshot: vi.fn(),
      writeRawResponse: vi.fn(),
      writeShotScriptVersion: vi.fn(),
      readShotScriptVersion: vi.fn(),
      writeCurrentShotScript: vi.fn(),
      readCurrentShotScript: vi.fn().mockResolvedValue({
        id: "shot_script_v1",
        title: "Episode 1 Shot Script",
        sourceStoryboardId: "storyboard_v1",
        sourceTaskId: "task_shot_script",
        updatedAt: "2026-03-24T00:10:00.000Z",
        approvedAt: "2026-03-24T00:10:00.000Z",
        segmentCount: 1,
        shotCount: 1,
        totalDurationSec: 3,
        segments: [
          {
            segmentId: "segment_1",
            sceneId: "scene_1",
            order: 1,
            name: "集市压境",
            summary: "林夏确认对手已经堵住出口。",
            durationSec: 3,
            status: "approved",
            lastGeneratedAt: "2026-03-24T00:09:00.000Z",
            approvedAt: "2026-03-24T00:10:00.000Z",
            shots: [
              {
                id: "shot_1",
                sceneId: "scene_1",
                segmentId: "segment_1",
                order: 1,
                shotCode: "S01-SG01-SH01",
                durationSec: 3,
                purpose: "交代堵路。",
                visual: "清晨积水集市入口。",
                subject: "林夏",
                action: "她停住脚步。",
                frameDependency: "start_and_end_frame",
                dialogue: null,
                os: null,
                audio: "雨声与水声。",
                transitionHint: null,
                continuityNotes: null,
              },
            ],
          },
        ],
      }),
    };
    const characterSheetRepository = {
      insertBatch: vi.fn(),
      findBatchById: vi.fn(),
      listCharactersByBatchId: vi.fn().mockResolvedValue([]),
      insertCharacter: vi.fn(),
      findCharacterById: vi.fn(),
      updateCharacter: vi.fn(),
    };
    const characterSheetStorage = {
      initializePromptTemplate: vi.fn(),
      readPromptTemplate: vi.fn(),
      writeBatchManifest: vi.fn(),
      writeGeneratedPrompt: vi.fn(),
      writeImageVersion: vi.fn(),
      writeCurrentImage: vi.fn(),
      readCurrentCharacterSheet: vi.fn(),
      listReferenceImages: vi.fn(),
      saveReferenceImages: vi.fn(),
      deleteReferenceImage: vi.fn(),
      getReferenceImageContent: vi.fn(),
      getImageContent: vi.fn(),
      resolveReferenceImagePaths: vi.fn(),
    };
    const framePromptProvider = {
      generateFramePrompt: vi.fn().mockResolvedValue({
        frameType: "start_frame",
        selectedCharacterIds: [],
        promptText: "新的起始帧提示词。",
        negativePromptText: null,
        rationale: "聚焦镜头起始状态。",
        rawResponse: "{}",
        provider: "gemini",
        model: "gemini-3.1-pro-preview",
      }),
    };

    const useCase = createProcessFramePromptGenerateTaskUseCase({
      taskRepository,
      projectRepository,
      taskFileStorage,
      shotImageRepository,
      shotImageStorage,
      shotScriptStorage,
      characterSheetRepository,
      characterSheetStorage,
      framePromptProvider,
      clock: {
        now: vi
          .fn()
          .mockReturnValueOnce("2026-03-24T00:14:00.000Z")
          .mockReturnValueOnce("2026-03-24T00:15:00.000Z"),
      },
    });

    await useCase.execute({ taskId: "task_frame_prompt_4" });

    expect(shotImageRepository.updateFrame).toHaveBeenCalledWith(
      expect.objectContaining({
        id: shot.startFrame.id,
        promptTextCurrent: "新的起始帧提示词。",
        planStatus: "planned",
        sourceTaskId: "task_frame_prompt_4",
      }),
    );
    expect(shotImageRepository.updateShot).not.toHaveBeenCalled();
  });
});
