import crypto from "node:crypto";

import {
  createApproveAllImageFramesUseCase,
  createApproveAllVideoSegmentsUseCase,
  createApproveAllShotScriptSegmentsUseCase,
  createApproveCharacterSheetUseCase,
  createApproveSceneSheetUseCase,
  createApproveImageFrameUseCase,
  createApproveVideoSegmentUseCase,
  createApproveMasterPlotUseCase,
  createApproveShotScriptSegmentUseCase,
  createApproveStoryboardUseCase,
  createCreateImagesGenerateTaskUseCase,
  createCreateImageBatchGenerateAllFramesTaskUseCase,
  createCreateImageBatchRegenerateAllPromptsTaskUseCase,
  createCreateImageBatchRegenerateFailedFramesTaskUseCase,
  createCreateImageBatchRegenerateFailedPromptsTaskUseCase,
  createCreateMasterPlotGenerateTaskUseCase,
  createCreateCharacterSheetsGenerateTaskUseCase,
  createCreateSceneSheetsGenerateTaskUseCase,
  createCreateFinalCutGenerateTaskUseCase,
  createCreateShotScriptGenerateTaskUseCase,
  createCreateStoryboardGenerateTaskUseCase,
  createCreateProjectUseCase,
  createCreateVideosGenerateTaskUseCase,
  createAddCharacterSheetReferenceImagesUseCase,
  createDeleteCharacterSheetReferenceImageUseCase,
  createGetCharacterSheetImageContentUseCase,
  createGetCharacterSheetUseCase,
  createGetCharacterSheetReferenceImageContentUseCase,
  createGetFinalCutUseCase,
  createGetImageFrameUseCase,
  createGetImageFrameContentUseCase,
  createGetProjectAssetContentUseCase,
  createGetCurrentShotScriptUseCase,
  createGetCurrentStoryboardUseCase,
  createGetMasterPlotReviewUseCase,
  createGetProjectDetailUseCase,
  createGetShotScriptReviewUseCase,
  createGetStoryboardReviewUseCase,
  createGetTaskDetailUseCase,
  createGetVideoUseCase,
  createListCharacterSheetsUseCase,
  createListSceneSheetsUseCase,
  createListImagesUseCase,
  createListVideosUseCase,
  createListProjectsUseCase,
  createGenerateFrameImageUseCase,
  createRegenerateAllFramePromptsUseCase,
  createRegenerateFailedFrameImagesUseCase,
  createRegenerateFailedFramePromptsUseCase,
  createRegenerateUnfinishedFramePromptsUseCase,
  createRegenerateAllVideoPromptsUseCase,
  createRegenerateCharacterSheetsUseCase,
  createRegenerateShotScriptSegmentUseCase,
  createRegenerateImagesUseCase,
  createRegenerateVideoPromptUseCase,
  createRegenerateVideoSegmentUseCase,
  createRegenerateMasterPlotUseCase,
  createRegenerateCharacterSheetUseCase,
  createRegenerateSceneSheetUseCase,
  createRegenerateFramePromptUseCase,
  createRegenerateShotScriptUseCase,
  createRegenerateStoryboardUseCase,
  createResetProjectPremiseUseCase,
  createRejectMasterPlotUseCase,
  createRejectStoryboardUseCase,
  createSaveSegmentVideoConfigUseCase,
  createSaveHumanMasterPlotUseCase,
  createSaveHumanShotScriptSegmentUseCase,
  createSaveHumanStoryboardVersionUseCase,
  createUploadSegmentVideoAudioUseCase,
  createUpdateCharacterSheetPromptUseCase,
  createUpdateSceneSheetPromptUseCase,
  createUpdateFramePromptUseCase,
  createUpdateProjectUseCase,
  createUpdateVideoPromptUseCase,
  createUpdateProjectScriptUseCase,
} from "@sweet-star/core";
import type { Spec1Infrastructure } from "./spec1-infrastructure";
import type { Spec1TaskQueue } from "./spec1-task-queue";

export interface CreateSpec1UseCasesOptions {
  infrastructure: Spec1Infrastructure;
  taskQueue: Spec1TaskQueue;
}

export function createSpec1UseCases({
  infrastructure,
  taskQueue,
}: CreateSpec1UseCasesOptions) {
  const {
    repository,
    premiseStorage,
    taskRepository,
    taskFileStorage,
    storyboardStorage,
    shotScriptStorage,
    characterSheetRepository,
    sceneSheetRepository,
    shotImageRepository,
    videoRepository,
    shotScriptReviewRepository,
    characterSheetStorage,
    sceneSheetStorage,
    shotImageStorage,
    videoStorage,
    videoPromptProvider,
    masterPlotStorage,
    clock,
  } = infrastructure;
  const { taskQueue: queuedTaskGateway, taskIdGenerator } = taskQueue;

  const createCharacterSheetsGenerateTask = createCreateCharacterSheetsGenerateTaskUseCase({
    projectRepository: repository,
    masterPlotStorage,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });
  const createSceneSheetsGenerateTask = createCreateSceneSheetsGenerateTaskUseCase({
    projectRepository: repository,
    masterPlotStorage,
    characterSheetRepository,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });

  const createMasterPlotGenerateTask = createCreateMasterPlotGenerateTaskUseCase({
    projectRepository: repository,
    premiseStorage,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });

  const createStoryboardGenerateTask = createCreateStoryboardGenerateTaskUseCase({
    projectRepository: repository,
    masterPlotStorage,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });
  const createShotScriptGenerateTask = createCreateShotScriptGenerateTaskUseCase({
    projectRepository: repository,
    storyboardStorage,
    masterPlotStorage,
    characterSheetRepository,
    characterSheetStorage,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });
  const createImagesGenerateTask = createCreateImagesGenerateTaskUseCase({
    projectRepository: repository,
    shotScriptStorage,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });
  const createVideosGenerateTask = createCreateVideosGenerateTaskUseCase({
    projectRepository: repository,
    shotImageRepository,
    shotScriptStorage,
    storyboardStorage,
    masterPlotStorage,
    characterSheetRepository,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });
  const createFinalCutGenerateTask = createCreateFinalCutGenerateTaskUseCase({
    projectRepository: repository,
    videoRepository,
    taskRepository,
    taskFileStorage,
    taskQueue: queuedTaskGateway,
    taskIdGenerator,
    clock,
  });
  const createImageBatchGenerateAllFramesTask =
    createCreateImageBatchGenerateAllFramesTaskUseCase({
      projectRepository: repository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    });
  const createImageBatchRegenerateFailedFramesTask =
    createCreateImageBatchRegenerateFailedFramesTaskUseCase({
      projectRepository: repository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    });
  const createImageBatchRegenerateAllPromptsTask =
    createCreateImageBatchRegenerateAllPromptsTaskUseCase({
      projectRepository: repository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    });
  const createImageBatchRegenerateFailedPromptsTask =
    createCreateImageBatchRegenerateFailedPromptsTaskUseCase({
      projectRepository: repository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    });
  return {
    createProject: createCreateProjectUseCase({
      repository,
      premiseStorage,
      masterPlotStorage,
      idGenerator: {
        generateProjectId: () => {
          const datePart = new Date().toISOString().slice(0, 10).replaceAll("-", "");
          const randomPart = crypto.randomBytes(3).toString("hex");

          return `proj_${datePart}_${randomPart}`;
        },
      },
      clock,
    }),
    listProjects: createListProjectsUseCase({
      repository,
      masterPlotStorage,
      storyboardStorage,
      shotScriptStorage,
      characterSheetRepository,
      sceneSheetRepository,
      shotImageRepository,
      videoRepository,
    }),
    getProjectDetail: createGetProjectDetailUseCase({
      repository,
      premiseStorage,
      masterPlotStorage,
      storyboardStorage,
      shotScriptStorage,
      characterSheetRepository,
      sceneSheetRepository,
      shotImageRepository,
      videoRepository,
    }),
    listCharacterSheets: createListCharacterSheetsUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
    }),
    listSceneSheets: createListSceneSheetsUseCase({
      projectRepository: repository,
      sceneSheetRepository,
    }),
    addCharacterSheetReferenceImages: createAddCharacterSheetReferenceImagesUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
      clock,
    }),
    deleteCharacterSheetReferenceImage: createDeleteCharacterSheetReferenceImageUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
    }),
    getCharacterSheet: createGetCharacterSheetUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
    }),
    getCharacterSheetImageContent: createGetCharacterSheetImageContentUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
    }),
    getCharacterSheetReferenceImageContent: createGetCharacterSheetReferenceImageContentUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
    }),
    getCurrentStoryboard: createGetCurrentStoryboardUseCase({
      storyboardStorage,
      projectRepository: repository,
    }),
    getCurrentShotScript: createGetCurrentShotScriptUseCase({
      shotScriptStorage,
      projectRepository: repository,
    }),
    listImages: createListImagesUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      shotImageRepository,
      shotImageStorage,
    }),
    listVideos: createListVideosUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotImageRepository,
      videoStorage,
      videoPromptProvider,
      videoRepository,
    }),
    getFinalCut: createGetFinalCutUseCase({
      projectRepository: repository,
      videoRepository,
    }),
    getImageFrame: createGetImageFrameUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      shotImageRepository,
      shotImageStorage,
    }),
    getVideo: createGetVideoUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotImageRepository,
      videoStorage,
      videoPromptProvider,
      videoRepository,
    }),
    getImageFrameContent: createGetImageFrameContentUseCase({
      projectRepository: repository,
      shotImageRepository,
      shotImageStorage,
    }),
    getProjectAssetContent: createGetProjectAssetContentUseCase({
      projectRepository: repository,
      shotImageStorage,
    }),
    getMasterPlotReview: createGetMasterPlotReviewUseCase({
      projectRepository: repository,
      masterPlotStorage,
      taskRepository,
    }),
    getStoryboardReview: createGetStoryboardReviewUseCase({
      projectRepository: repository,
      storyboardStorage,
      taskRepository,
    }),
    getShotScriptReview: createGetShotScriptReviewUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotScriptReviewRepository,
      taskRepository,
    }),
    updateProjectScript: createUpdateProjectScriptUseCase({
      repository,
      premiseStorage,
      clock,
    }),
    updateProject: createUpdateProjectUseCase({
      repository,
      clock,
    }),
    resetProjectPremise: createResetProjectPremiseUseCase({
      repository,
      premiseStorage,
      masterPlotStorage,
      clock,
    }),
    saveHumanMasterPlot: createSaveHumanMasterPlotUseCase({
      projectRepository: repository,
      masterPlotStorage,
      clock,
    }),
    saveHumanStoryboardVersion: createSaveHumanStoryboardVersionUseCase({
      projectRepository: repository,
      storyboardStorage,
      clock,
    }),
    saveHumanShotScriptSegment: createSaveHumanShotScriptSegmentUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
      shotScriptStorage,
      clock,
    }),
    approveMasterPlot: createApproveMasterPlotUseCase({
      projectRepository: repository,
      masterPlotStorage,
      clock,
    }),
    approveStoryboard: createApproveStoryboardUseCase({
      projectRepository: repository,
      storyboardStorage,
      clock,
    }),
    approveShotScriptSegment: createApproveShotScriptSegmentUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotScriptReviewRepository,
      clock,
    }),
    approveAllShotScriptSegments: createApproveAllShotScriptSegmentsUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotScriptReviewRepository,
      clock,
    }),
    rejectMasterPlot: createRejectMasterPlotUseCase({
      projectRepository: repository,
      masterPlotStorage,
      createMasterPlotGenerateTask,
    }),
    rejectStoryboard: createRejectStoryboardUseCase({
      projectRepository: repository,
      storyboardStorage,
      createStoryboardGenerateTask,
    }),
    regenerateMasterPlot: createRegenerateMasterPlotUseCase({
      projectRepository: repository,
      createMasterPlotGenerateTask,
      clock,
    }),
    regenerateCharacterSheets: createRegenerateCharacterSheetsUseCase({
      projectRepository: repository,
      createCharacterSheetsGenerateTask,
      clock,
    }),
    regenerateStoryboard: createRegenerateStoryboardUseCase({
      projectRepository: repository,
      createStoryboardGenerateTask,
      clock,
    }),
    regenerateShotScript: createRegenerateShotScriptUseCase({
      projectRepository: repository,
      createShotScriptGenerateTask,
      clock,
    }),
    regenerateImages: createRegenerateImagesUseCase({
      projectRepository: repository,
      createImagesGenerateTask,
      clock,
    }),
    regenerateVideoSegment: createRegenerateVideoSegmentUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotImageRepository,
      videoRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    regenerateShotScriptSegment: createRegenerateShotScriptSegmentUseCase({
      projectRepository: repository,
      storyboardStorage,
      shotScriptStorage,
      shotScriptReviewRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    updateCharacterSheetPrompt: createUpdateCharacterSheetPromptUseCase({
      projectRepository: repository,
      characterSheetRepository,
      clock,
    }),
    updateSceneSheetPrompt: createUpdateSceneSheetPromptUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      clock,
    }),
    updateFramePrompt: createUpdateFramePromptUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      shotImageRepository,
      shotImageStorage,
      clock,
    }),
    updateVideoPrompt: createUpdateVideoPromptUseCase({
      projectRepository: repository,
      videoRepository,
      clock,
    }),
    saveSegmentVideoConfig: createSaveSegmentVideoConfigUseCase({
      projectRepository: repository,
      videoRepository,
      clock,
    }),
    uploadSegmentVideoAudio: createUploadSegmentVideoAudioUseCase({
      projectRepository: repository,
      videoRepository,
      videoStorage,
      clock,
    }),
    regenerateCharacterSheet: createRegenerateCharacterSheetUseCase({
      projectRepository: repository,
      characterSheetRepository,
      characterSheetStorage,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    regenerateSceneSheet: createRegenerateSceneSheetUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    regenerateFramePrompt: createRegenerateFramePromptUseCase({
      projectRepository: repository,
      shotImageRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    regenerateVideoPrompt: createRegenerateVideoPromptUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotImageRepository,
      characterSheetRepository,
      sceneSheetRepository,
      videoRepository,
      videoStorage,
      videoPromptProvider,
      clock,
    }),
    regenerateAllVideoPrompts: createRegenerateAllVideoPromptsUseCase({
      projectRepository: repository,
      shotScriptStorage,
      shotImageRepository,
      characterSheetRepository,
      sceneSheetRepository,
      videoRepository,
      videoStorage,
      videoPromptProvider,
      clock,
    }),
    regenerateAllFramePrompts: createRegenerateAllFramePromptsUseCase({
      projectRepository: repository,
      shotImageRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    regenerateFailedFramePrompts: createRegenerateFailedFramePromptsUseCase({
      projectRepository: repository,
      shotImageRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    regenerateUnfinishedFramePrompts: createRegenerateUnfinishedFramePromptsUseCase({
      projectRepository: repository,
      shotImageRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    regenerateFailedFrameImages: createRegenerateFailedFrameImagesUseCase({
      projectRepository: repository,
      shotImageRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    generateFrameImage: createGenerateFrameImageUseCase({
      projectRepository: repository,
      shotImageRepository,
      taskRepository,
      taskFileStorage,
      taskQueue: queuedTaskGateway,
      taskIdGenerator,
      clock,
    }),
    approveCharacterSheet: createApproveCharacterSheetUseCase({
      projectRepository: repository,
      characterSheetRepository,
      clock,
    }),
    approveSceneSheet: createApproveSceneSheetUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      clock,
    }),
    approveImageFrame: createApproveImageFrameUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      shotImageRepository,
      shotImageStorage,
      clock,
    }),
    approveVideoSegment: createApproveVideoSegmentUseCase({
      projectRepository: repository,
      videoRepository,
      clock,
    }),
    approveAllImageFrames: createApproveAllImageFramesUseCase({
      projectRepository: repository,
      sceneSheetRepository,
      shotImageRepository,
      shotImageStorage,
      clock,
    }),
    approveAllVideoSegments: createApproveAllVideoSegmentsUseCase({
      projectRepository: repository,
      videoRepository,
      clock,
    }),
    createMasterPlotGenerateTask,
    createCharacterSheetsGenerateTask,
    createSceneSheetsGenerateTask,
    createStoryboardGenerateTask,
    createShotScriptGenerateTask,
    createImagesGenerateTask,
    createImageBatchGenerateAllFramesTask,
    createImageBatchRegenerateFailedFramesTask,
    createImageBatchRegenerateAllPromptsTask,
    createImageBatchRegenerateFailedPromptsTask,
    createVideosGenerateTask,
    createFinalCutGenerateTask,
    getTaskDetail: createGetTaskDetailUseCase({
      repository: taskRepository,
    }),
  };
}
